//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.01 at 02:46:19 PM BRT 
//


package webservice.nfse.uberlandia;
import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;


/**
 * Lote de RPS
 * 
 * 
 */
@XStreamAlias(value = "Lote")
public class TpLote {

	@XStreamAlias(value = "RPS")
    protected TpRPS rps;
	@XStreamAsAttribute
	@XStreamAlias(value = "Id")
    protected String id;

    public TpRPS getRps() {
    	if(rps == null) {
    		rps = new TpRPS();
    	}
		return rps;
	}

	public void setRps(TpRPS rps) {
		this.rps = rps;
	}

	/**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

	@Override
	public String toString() {
		return "TpLote [RPS=" + rps + ", Id=" + id + "]";
	}
}
