//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.01 at 02:46:19 PM BRT 
//


package webservice.nfse.uberlandia;
import java.math.BigDecimal;
import java.util.List;

import javax.xml.datatype.XMLGregorianCalendar;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;


/**
 * Tipo que representa um RPS.
 * 
 * 
 */
@XStreamAlias(value = "RPS")
public class TpRPS {

	@XStreamAlias("Assinatura")
    protected String assinatura;
	@XStreamAlias("InscricaoMunicipalPrestador")
    protected String inscricaoMunicipalPrestador;
	@XStreamAlias("RazaoSocialPrestador")
    protected String razaoSocialPrestador;
	@XStreamAlias("TipoRPS")
    protected TpTipoRPS tipoRPS;
	@XStreamAlias("SerieRPS")
    protected TpSerieRPS serieRPS;
	@XStreamAlias("NumeroRPS")
    protected Long numeroRPS;
	@XStreamAlias("DataEmissaoRPS")
    protected String dataEmissaoRPS;
	@XStreamAlias("SituacaoRPS")
    protected TpSituacaoRPS situacaoRPS;
	@XStreamAlias("SerieRPSSubstituido")
    protected String serieRPSSubstituido;
	@XStreamAlias("NumeroRPSSubstituido")
    protected Integer numeroRPSSubstituido;
	@XStreamAlias("NumeroNFSeSubstituida")
    protected Integer numeroNFSeSubstituida;
	@XStreamAlias("DataEmissaoNFSeSubstituida")
    protected String dataEmissaoNFSeSubstituida;
	@XStreamAlias("SeriePrestacao")
    protected String seriePrestacao;
	@XStreamAlias("InscricaoMunicipalTomador")
    protected String inscricaoMunicipalTomador;
	@XStreamAlias("CPFCNPJTomador")
    protected String cpfcnpjTomador;
	@XStreamAlias("RazaoSocialTomador")
    protected String razaoSocialTomador;
	@XStreamAlias("DocTomadorEstrangeiro")
    protected String docTomadorEstrangeiro;
	@XStreamAlias("TipoLogradouroTomador")
    protected String tipoLogradouroTomador;
	@XStreamAlias("LogradouroTomador")
    protected String logradouroTomador;
	@XStreamAlias("NumeroEnderecoTomador")
    protected String numeroEnderecoTomador;
	@XStreamAlias("ComplementoEnderecoTomador")
    protected String complementoEnderecoTomador;
	@XStreamAlias("TipoBairroTomador")
    protected String tipoBairroTomador;
	@XStreamAlias("BairroTomador")
    protected String bairroTomador;
	@XStreamAlias("CidadeTomador")
    protected String cidadeTomador;
	@XStreamAlias("CidadeTomadorDescricao")
    protected String cidadeTomadorDescricao;
	@XStreamAlias("CEPTomador")
    protected String cepTomador;
	@XStreamAlias("EmailTomador")
    protected String emailTomador;
	@XStreamAlias("CodigoAtividade")
    protected String codigoAtividade;
	@XStreamAlias("AliquotaAtividade")
    protected String aliquotaAtividade;
	@XStreamAlias("TipoRecolhimento")
    protected TpTipoRecolhimento tipoRecolhimento;
	@XStreamAlias("MunicipioPrestacao")
    protected String municipioPrestacao;
	@XStreamAlias("MunicipioPrestacaoDescricao")
    protected String municipioPrestacaoDescricao;
	@XStreamAlias("Operacao")
    protected TpOperacao operacao;
	@XStreamAlias("Tributacao")
    protected TpTributacao tributacao;
	@XStreamAlias("ValorPIS")
    protected BigDecimal valorPIS;
	@XStreamAlias("ValorCOFINS")
    protected BigDecimal valorCOFINS;
	@XStreamAlias("ValorINSS")
    protected BigDecimal valorINSS;
	@XStreamAlias("ValorIR")
    protected BigDecimal valorIR;
	@XStreamAlias("ValorCSLL")
    protected BigDecimal valorCSLL;
	@XStreamAlias("AliquotaPIS")
    protected BigDecimal aliquotaPIS;
	@XStreamAlias("AliquotaCOFINS")
    protected BigDecimal aliquotaCOFINS;
	@XStreamAlias("AliquotaINSS")
    protected BigDecimal aliquotaINSS;
	@XStreamAlias("AliquotaIR")
    protected BigDecimal aliquotaIR;
	@XStreamAlias("AliquotaCSLL")
    protected BigDecimal aliquotaCSLL;
	@XStreamAlias("DescricaoRPS")
    protected String descricaoRPS;
	@XStreamAlias("DDDPrestador")
    protected String dddPrestador;
	@XStreamAlias("TelefonePrestador")
    protected String telefonePrestador;
	@XStreamAlias("DDDTomador")
    protected String dddTomador;
	@XStreamAlias("TelefoneTomador")
    protected String telefoneTomador;
	@XStreamAlias("MotCancelamento")
    protected String motCancelamento;
	@XStreamAlias("CPFCNPJIntermediario")
    protected String cpfcnpjIntermediario;
	@XStreamAlias("Deducoes")
	List<TpDeducoes> deducoes;	
	@XStreamAlias("Itens")
    protected TpListaItens itens;
	@XStreamAsAttribute
	@XStreamAlias("Id")
    protected String id;


    public String getAssinatura() {
		return assinatura;
	}

	public void setAssinatura(String assinatura) {
		this.assinatura = assinatura;
	}

	/**
     * Gets the value of the inscricaoMunicipalPrestador property.
     * 
     */
    public String getInscricaoMunicipalPrestador() {
        return inscricaoMunicipalPrestador;
    }

    /**
     * Sets the value of the inscricaoMunicipalPrestador property.
     * 
     */
    public void setInscricaoMunicipalPrestador(String value) {
        this.inscricaoMunicipalPrestador = value;
    }

    /**
     * Gets the value of the razaoSocialPrestador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRazaoSocialPrestador() {
        return razaoSocialPrestador;
    }

    /**
     * Sets the value of the razaoSocialPrestador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRazaoSocialPrestador(String value) {
        this.razaoSocialPrestador = value;
    }

    /**
     * Gets the value of the tipoRPS property.
     * 
     * @return
     *     possible object is
     *     {@link TpTipoRPS }
     *     
     */
    public TpTipoRPS getTipoRPS() {
        return tipoRPS;
    }

    /**
     * Sets the value of the tipoRPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpTipoRPS }
     *     
     */
    public void setTipoRPS(TpTipoRPS value) {
        this.tipoRPS = value;
    }

    /**
     * Gets the value of the serieRPS property.
     * 
     * @return
     *     possible object is
     *     {@link TpSerieRPS }
     *     
     */
    public TpSerieRPS getSerieRPS() {
        return serieRPS;
    }

    /**
     * Sets the value of the serieRPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpSerieRPS }
     *     
     */
    public void setSerieRPS(TpSerieRPS value) {
        this.serieRPS = value;
    }

    /**
     * Gets the value of the numeroRPS property.
     * 
     */
    public Long getNumeroRPS() {
        return numeroRPS;
    }

    /**
     * Sets the value of the numeroRPS property.
     * 
     */
    public void setNumeroRPS(Long value) {
        this.numeroRPS = value;
    }

    /**
     * Gets the value of the dataEmissaoRPS property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getDataEmissaoRPS() {
        return dataEmissaoRPS;
    }

    /**
     * Sets the value of the dataEmissaoRPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataEmissaoRPS(String value) {
        this.dataEmissaoRPS = value;
    }

    /**
     * Gets the value of the situacaoRPS property.
     * 
     * @return
     *     possible object is
     *     {@link TpSituacaoRPS }
     *     
     */
    public TpSituacaoRPS getSituacaoRPS() {
        return situacaoRPS;
    }

    /**
     * Sets the value of the situacaoRPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpSituacaoRPS }
     *     
     */
    public void setSituacaoRPS(TpSituacaoRPS value) {
        this.situacaoRPS = value;
    }

    /**
     * Gets the value of the serieRPSSubstituido property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerieRPSSubstituido() {
        return serieRPSSubstituido;
    }

    /**
     * Sets the value of the serieRPSSubstituido property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerieRPSSubstituido(String value) {
        this.serieRPSSubstituido = value;
    }

    /**
     * Gets the value of the numeroRPSSubstituido property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumeroRPSSubstituido() {
        return numeroRPSSubstituido;
    }

    /**
     * Sets the value of the numeroRPSSubstituido property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumeroRPSSubstituido(Integer value) {
        this.numeroRPSSubstituido = value;
    }

    /**
     * Gets the value of the numeroNFSeSubstituida property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumeroNFSeSubstituida() {
        return numeroNFSeSubstituida;
    }

    /**
     * Sets the value of the numeroNFSeSubstituida property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumeroNFSeSubstituida(Integer value) {
        this.numeroNFSeSubstituida = value;
    }

    /**
     * Gets the value of the dataEmissaoNFSeSubstituida property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataEmissaoNFSeSubstituida() {
        return dataEmissaoNFSeSubstituida;
    }

    /**
     * Sets the value of the dataEmissaoNFSeSubstituida property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataEmissaoNFSeSubstituida(String value) {
        this.dataEmissaoNFSeSubstituida = value;
    }

    /**
     * Gets the value of the seriePrestacao property.
     * 
     */
    public String getSeriePrestacao() {
        return seriePrestacao;
    }

    /**
     * Sets the value of the seriePrestacao property.
     * 
     */
    public void setSeriePrestacao(String value) {
        this.seriePrestacao = value;
    }

    /**
     * Gets the value of the inscricaoMunicipalTomador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInscricaoMunicipalTomador() {
        return inscricaoMunicipalTomador;
    }

    /**
     * Sets the value of the inscricaoMunicipalTomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInscricaoMunicipalTomador(String value) {
        this.inscricaoMunicipalTomador = value;
    }

    /**
     * Gets the value of the cpfcnpjTomador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPFCNPJTomador() {
        return cpfcnpjTomador;
    }

    /**
     * Sets the value of the cpfcnpjTomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPFCNPJTomador(String value) {
        this.cpfcnpjTomador = value;
    }

    /**
     * Gets the value of the razaoSocialTomador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRazaoSocialTomador() {
        return razaoSocialTomador;
    }

    /**
     * Sets the value of the razaoSocialTomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRazaoSocialTomador(String value) {
        this.razaoSocialTomador = value;
    }

    /**
     * Gets the value of the docTomadorEstrangeiro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocTomadorEstrangeiro() {
        return docTomadorEstrangeiro;
    }

    /**
     * Sets the value of the docTomadorEstrangeiro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocTomadorEstrangeiro(String value) {
        this.docTomadorEstrangeiro = value;
    }

    /**
     * Gets the value of the tipoLogradouroTomador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoLogradouroTomador() {
        return tipoLogradouroTomador;
    }

    /**
     * Sets the value of the tipoLogradouroTomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoLogradouroTomador(String value) {
        this.tipoLogradouroTomador = value;
    }

    /**
     * Gets the value of the logradouroTomador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogradouroTomador() {
        return logradouroTomador;
    }

    /**
     * Sets the value of the logradouroTomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogradouroTomador(String value) {
        this.logradouroTomador = value;
    }

    /**
     * Gets the value of the numeroEnderecoTomador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroEnderecoTomador() {
        return numeroEnderecoTomador;
    }

    /**
     * Sets the value of the numeroEnderecoTomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroEnderecoTomador(String value) {
        this.numeroEnderecoTomador = value;
    }

    /**
     * Gets the value of the complementoEnderecoTomador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComplementoEnderecoTomador() {
        return complementoEnderecoTomador;
    }

    /**
     * Sets the value of the complementoEnderecoTomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComplementoEnderecoTomador(String value) {
        this.complementoEnderecoTomador = value;
    }

    /**
     * Gets the value of the tipoBairroTomador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoBairroTomador() {
        return tipoBairroTomador;
    }

    /**
     * Sets the value of the tipoBairroTomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoBairroTomador(String value) {
        this.tipoBairroTomador = value;
    }

    /**
     * Gets the value of the bairroTomador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBairroTomador() {
        return bairroTomador;
    }

    /**
     * Sets the value of the bairroTomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBairroTomador(String value) {
        this.bairroTomador = value;
    }

    /**
     * Gets the value of the cidadeTomador property.
     * 
     */
    public String getCidadeTomador() {
        return cidadeTomador;
    }

    /**
     * Sets the value of the cidadeTomador property.
     * 
     */
    public void setCidadeTomador(String value) {
        this.cidadeTomador = value;
    }

    /**
     * Gets the value of the cidadeTomadorDescricao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCidadeTomadorDescricao() {
        return cidadeTomadorDescricao;
    }

    /**
     * Sets the value of the cidadeTomadorDescricao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCidadeTomadorDescricao(String value) {
        this.cidadeTomadorDescricao = value;
    }

    /**
     * Gets the value of the cepTomador property.
     * 
     */
    public String getCEPTomador() {
        return cepTomador;
    }

    /**
     * Sets the value of the cepTomador property.
     * 
     */
    public void setCEPTomador(String value) {
        this.cepTomador = value;
    }

    /**
     * Gets the value of the emailTomador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailTomador() {
        return emailTomador;
    }

    /**
     * Sets the value of the emailTomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailTomador(String value) {
        this.emailTomador = value;
    }

    /**
     * Gets the value of the codigoAtividade property.
     * 
     */
    public String getCodigoAtividade() {
        return codigoAtividade;
    }

    /**
     * Sets the value of the codigoAtividade property.
     * 
     */
    public void setCodigoAtividade(String value) {
        this.codigoAtividade = value;
    }

    /**
     * Gets the value of the aliquotaAtividade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAliquotaAtividade() {
        return aliquotaAtividade;
    }

    /**
     * Sets the value of the aliquotaAtividade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliquotaAtividade(String value) {
        this.aliquotaAtividade = value;
    }

    /**
     * Gets the value of the tipoRecolhimento property.
     * 
     * @return
     *     possible object is
     *     {@link TpTipoRecolhimento }
     *     
     */
    public TpTipoRecolhimento getTipoRecolhimento() {
        return tipoRecolhimento;
    }

    /**
     * Sets the value of the tipoRecolhimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpTipoRecolhimento }
     *     
     */
    public void setTipoRecolhimento(TpTipoRecolhimento value) {
        this.tipoRecolhimento = value;
    }

    /**
     * Gets the value of the municipioPrestacao property.
     * 
     */
    public String getMunicipioPrestacao() {
        return municipioPrestacao;
    }

    /**
     * Sets the value of the municipioPrestacao property.
     * 
     */
    public void setMunicipioPrestacao(String value) {
        this.municipioPrestacao = value;
    }

    /**
     * Gets the value of the municipioPrestacaoDescricao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMunicipioPrestacaoDescricao() {
        return municipioPrestacaoDescricao;
    }

    /**
     * Sets the value of the municipioPrestacaoDescricao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMunicipioPrestacaoDescricao(String value) {
        this.municipioPrestacaoDescricao = value;
    }

    /**
     * Gets the value of the operacao property.
     * 
     * @return
     *     possible object is
     *     {@link TpOperacao }
     *     
     */
    public TpOperacao getOperacao() {
        return operacao;
    }

    /**
     * Sets the value of the operacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpOperacao }
     *     
     */
    public void setOperacao(TpOperacao value) {
        this.operacao = value;
    }

    /**
     * Gets the value of the tributacao property.
     * 
     * @return
     *     possible object is
     *     {@link TpTributacao }
     *     
     */
    public TpTributacao getTributacao() {
        return tributacao;
    }

    /**
     * Sets the value of the tributacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpTributacao }
     *     
     */
    public void setTributacao(TpTributacao value) {
        this.tributacao = value;
    }

    /**
     * Gets the value of the valorPIS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getValorPIS() {
        return valorPIS;
    }

    /**
     * Sets the value of the valorPIS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValorPIS(BigDecimal value) {
        this.valorPIS = value;
    }

    /**
     * Gets the value of the valorCOFINS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getValorCOFINS() {
        return valorCOFINS;
    }

    /**
     * Sets the value of the valorCOFINS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValorCOFINS(BigDecimal value) {
        this.valorCOFINS = value;
    }

    /**
     * Gets the value of the valorINSS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getValorINSS() {
        return valorINSS;
    }

    /**
     * Sets the value of the valorINSS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValorINSS(BigDecimal value) {
        this.valorINSS = value;
    }

    /**
     * Gets the value of the valorIR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getValorIR() {
        return valorIR;
    }

    /**
     * Sets the value of the valorIR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValorIR(BigDecimal value) {
        this.valorIR = value;
    }

    /**
     * Gets the value of the valorCSLL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getValorCSLL() {
        return valorCSLL;
    }

    /**
     * Sets the value of the valorCSLL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValorCSLL(BigDecimal value) {
        this.valorCSLL = value;
    }

    /**
     * Gets the value of the aliquotaPIS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getAliquotaPIS() {
        return aliquotaPIS;
    }

    /**
     * Sets the value of the aliquotaPIS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliquotaPIS(BigDecimal value) {
        this.aliquotaPIS = value;
    }

    /**
     * Gets the value of the aliquotaCOFINS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getAliquotaCOFINS() {
        return aliquotaCOFINS;
    }

    /**
     * Sets the value of the aliquotaCOFINS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliquotaCOFINS(BigDecimal value) {
        this.aliquotaCOFINS = value;
    }

    /**
     * Gets the value of the aliquotaINSS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getAliquotaINSS() {
        return aliquotaINSS;
    }

    /**
     * Sets the value of the aliquotaINSS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliquotaINSS(BigDecimal value) {
        this.aliquotaINSS = value;
    }

    /**
     * Gets the value of the aliquotaIR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getAliquotaIR() {
        return aliquotaIR;
    }

    /**
     * Sets the value of the aliquotaIR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliquotaIR(BigDecimal value) {
        this.aliquotaIR = value;
    }

    /**
     * Gets the value of the aliquotaCSLL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getAliquotaCSLL() {
        return aliquotaCSLL;
    }

    /**
     * Sets the value of the aliquotaCSLL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliquotaCSLL(BigDecimal value) {
        this.aliquotaCSLL = value;
    }

    /**
     * Gets the value of the descricaoRPS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescricaoRPS() {
        return descricaoRPS;
    }

    /**
     * Sets the value of the descricaoRPS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescricaoRPS(String value) {
        this.descricaoRPS = value;
    }

    /**
     * Gets the value of the dddPrestador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDDDPrestador() {
        return dddPrestador;
    }

    /**
     * Sets the value of the dddPrestador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDDDPrestador(String value) {
        this.dddPrestador = value;
    }

   
    public void setTelefoneTomador(String telefoneTomador) {
		this.telefoneTomador = telefoneTomador;
	}

	/**
     * Gets the value of the dddTomador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDDDTomador() {
        return dddTomador;
    }

    /**
     * Sets the value of the dddTomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDDDTomador(String value) {
        this.dddTomador = value;
    }


    public String getTelefonePrestador() {
		return telefonePrestador;
	}

	public void setTelefonePrestador(String telefonePrestador) {
		this.telefonePrestador = telefonePrestador;
	}

	/**
     * Sets the value of the motCancelamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotCancelamento(String value) {
        this.motCancelamento = value;
    }

    /**
     * Gets the value of the cpfcnpjIntermediario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPFCNPJIntermediario() {
        return cpfcnpjIntermediario;
    }

    /**
     * Sets the value of the cpfcnpjIntermediario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPFCNPJIntermediario(String value) {
        this.cpfcnpjIntermediario = value;
    }

    /**
     * Gets the value of the deducoes property.
     * 
     * @return
     *     possible object is
     *     {@link TpListaDeducoes }
     *     
     */
    public List<TpDeducoes> getDeducoes() {
        return deducoes;
    }

    /**
     * Sets the value of the deducoes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpListaDeducoes }
     *     
     */
    public void setDeducoes(List<TpDeducoes> value) {
        this.deducoes = value;
    }

    /**
     * Gets the value of the itens property.
     * 
     * @return
     *     possible object is
     *     {@link TpListaItens }
     *     
     */
    public TpListaItens getItens() {
        return itens;
    }

    /**
     * Sets the value of the itens property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpListaItens }
     *     
     */
    public void setItens(TpListaItens value) {
        this.itens = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

	@Override
	public String toString() {
		return "TpRPS [Assinatura=" + assinatura + ", InscricaoMunicipalPrestador=" + inscricaoMunicipalPrestador + ", RazaoSocialPrestador=" + razaoSocialPrestador + ", TipoRPS=" + tipoRPS + ", SerieRPS=" + serieRPS + ", NumeroRPS=" + numeroRPS + ", DataEmissaoRPS=" + dataEmissaoRPS + ", SituacaoRPS=" + situacaoRPS + ", SerieRPSSubstituido=" + serieRPSSubstituido + ", NumeroRPSSubstituido=" + numeroRPSSubstituido + ", NumeroNFSeSubstituida=" + numeroNFSeSubstituida + ", DataEmissaoNFSeSubstituida=" + dataEmissaoNFSeSubstituida + ", SeriePrestacao=" + seriePrestacao + ", InscricaoMunicipalTomador=" + inscricaoMunicipalTomador + ", CPFCNPJTomador=" + cpfcnpjTomador + ", RazaoSocialTomador=" + razaoSocialTomador + ", DocTomadorEstrangeiro=" + docTomadorEstrangeiro + ", TipoLogradouroTomador=" + tipoLogradouroTomador + ", LogradouroTomador=" + logradouroTomador + ", NumeroEnderecoTomador=" + numeroEnderecoTomador + ", ComplementoEnderecoTomador="
				+ complementoEnderecoTomador + ", TipoBairroTomador=" + tipoBairroTomador + ", BairroTomador=" + bairroTomador + ", CidadeTomador=" + cidadeTomador + ", CidadeTomadorDescricao=" + cidadeTomadorDescricao + ", CEPTomador=" + cepTomador + ", EmailTomador=" + emailTomador + ", CodigoAtividade=" + codigoAtividade + ", AliquotaAtividade=" + aliquotaAtividade + ", TipoRecolhimento=" + tipoRecolhimento + ", MunicipioPrestacao=" + municipioPrestacao + ", MunicipioPrestacaoDescricao=" + municipioPrestacaoDescricao + ", Operacao=" + operacao + ", Tributacao=" + tributacao + ", ValorPIS=" + valorPIS + ", ValorCOFINS=" + valorCOFINS + ", ValorINSS=" + valorINSS + ", ValorIR=" + valorIR + ", ValorCSLL=" + valorCSLL + ", AliquotaPIS=" + aliquotaPIS + ", AliquotaCOFINS=" + aliquotaCOFINS + ", AliquotaINSS=" + aliquotaINSS + ", AliquotaIR=" + aliquotaIR + ", AliquotaCSLL=" + aliquotaCSLL + ", DescricaoRPS=" + descricaoRPS + ", DDDPrestador=" + dddPrestador + ", TelefonePrestador="
				+ telefonePrestador + ", DDDTomador=" + dddTomador + ", TelefoneTomador=" + telefoneTomador + ", MotCancelamento=" + motCancelamento + ", CPFCNPJIntermediario=" + cpfcnpjIntermediario + ", Deducoes=" + deducoes + ", Itens=" + itens + ", Id=" + id + "]";
	}
}
