alter table if exists estagio  drop column if exists ano;
alter table if exists estagio  drop column if exists semestre;
alter table if exists estagio  drop column if exists empresa;
alter table if exists estagio  drop column if exists arquivo;
alter table if exists estagio  drop column if exists responsavel;
alter table if exists estagio  drop column if exists datacadastro;
alter table if exists estagio  drop column if exists apoliceseguro;
alter table if exists estagio  drop column if exists nomeseguradora;
alter table if exists estagio  drop column if exists cnpjseguradora;
alter table if exists estagio  drop column if exists telefoneseguradora;
alter table if exists estagio  drop column if exists dataassinaturaestagio;
alter table if exists estagio  drop column if exists valorbolsaestagio;
alter table if exists estagio  drop column if exists cargahorariasemanal;
alter table if exists estagio  drop column if exists areaatuacao;
alter table if exists estagio  drop column if exists cargofuncao;
alter table if exists estagio  drop column if exists empresaestagio;
alter table if exists estagio  drop column if exists nomesupervidorestagio;
alter table if exists estagio  drop column if exists telefonesupervisorestagio;
alter table if exists estagio  drop column if exists celularsupervisorestagio;
alter table if exists estagio  drop column if exists emailsupervisorestagio;
alter table if exists estagio  drop column if exists professorresponsavelestagio;
alter table if exists estagio  drop column if exists areaprofissional;
alter table if exists estagio  drop column if exists principalatividadeestagio;
alter table if exists estagio  drop column if exists cargohorariasemanal;
alter table if exists estagio  drop column if exists formacaoacademicasupervisorestagio;
alter table if exists estagio  drop column if exists registroconselhosupervisorestagio;
alter table if exists estagio  drop column if exists orgaoregistroconselhosupervisorestagio;
alter table if exists estagio  drop column if exists valorbolsaestagioanterior;
alter table if exists estagio  drop column if exists areaatuaaco;
alter table if exists estagio  drop column if exists auxiliotransporte;
alter table if exists estagio  drop column if exists localcampoestagio;
alter table if exists estagio  drop column if exists outracontraprestacao;
alter table if exists estagio  drop column if exists atividadeprofissionalexercicio;
alter table if exists estagio  drop column if exists datainicioempresa;
alter table if exists estagio  drop column if exists dataterminoempresa;
alter table if exists estagio  drop column if exists departamentoorgao;
alter table if exists estagio  drop column if exists cargafuncao;
alter table if exists estagio  drop column if exists jornadasemanaltrabalho;
alter table if exists estagio  drop column if exists enviadoseguradora;
alter table if exists estagio  drop column if exists dataenvioseguradora;
alter table if exists estagio  drop column if exists usuarioenvioseguradora;

alter table if exists estagio  add column if not exists concedente int;
alter table if exists estagio  add column if not exists gradecurricularestagio int;
alter table if exists estagio  add column if not exists documentoassinado int;
alter table if exists estagio  add column if not exists grupopessoaitem int;
alter table if exists estagio  add column if not exists situacaoestagioenum varchar(100) default 'AGUARDANDO_ASSINATURA';
alter table if exists estagio  add column if not exists situacaoadicionalestagioenum varchar(100) default 'AGUARDANDO_ASSINATURA';
alter table if exists estagio  add column if not exists nomeconcedente varchar(255);
alter table if exists estagio  add column if not exists tipoconcedente int4;
alter table if exists estagio  add column if not exists cnpj varchar(18);
alter table if exists estagio  add column if not exists telefone text ;
alter table if exists estagio  add column if not exists cep varchar(10);
alter table if exists estagio  add column if not exists endereco varchar(255);
alter table if exists estagio  add column if not exists	numero varchar(10);
alter table if exists estagio  add column if not exists	bairro varchar(255);
alter table if exists estagio  add column if not exists	complemento varchar(255);
alter table if exists estagio  add column if not exists	cidade int;
alter table if exists estagio  add column if not exists	responsavelconcedente varchar(255);
alter table if exists estagio  add column if not exists	cpfresponsavelconcedente varchar(14);
alter table if exists estagio  add column if not exists	emailresponsavelconcedente varchar(255);
alter table if exists estagio  add column if not exists	telefoneresponsavelconcedente text;
alter table if exists estagio  add column if not exists	motivo text;
alter table if exists estagio  add column if not exists	dataEnvioAnalise timestamp;
alter table if exists estagio  add column if not exists	dataLimiteAnalise timestamp;
alter table if exists estagio  add column if not exists	dataEnvioCorrecao timestamp;
alter table if exists estagio  add column if not exists	dataLimiteCorrecao timestamp;
alter table if exists estagio  add CONSTRAINT fk_estagio_concedente FOREIGN KEY (concedente) REFERENCES public.concedente(codigo) ON DELETE RESTRICT ON UPDATE restrict;
alter table if exists estagio  add CONSTRAINT fk_estagio_gradeCurricularEstagio FOREIGN KEY (gradeCurricularEstagio) REFERENCES public.gradeCurricularEstagio(codigo) ON DELETE RESTRICT ON UPDATE restrict;
alter table if exists estagio  add CONSTRAINT fk_estagio_cidade FOREIGN KEY (cidade) REFERENCES public.cidade(codigo) ON DELETE RESTRICT ON UPDATE restrict;
alter table if exists estagio  add CONSTRAINT fk_estagio_tipoconcedente FOREIGN KEY (tipoconcedente) REFERENCES public.tipoconcedente(codigo) ON DELETE RESTRICT ON UPDATE restrict;
alter table if exists estagio  add CONSTRAINT fk_estagio_documentoassinado FOREIGN KEY (documentoassinado) REFERENCES public.documentoassinado(codigo) ON DELETE RESTRICT ON UPDATE restrict;
alter table if exists estagio  add CONSTRAINT fk_estagio_grupopessoaitem FOREIGN KEY (grupopessoaitem) REFERENCES public.grupopessoaitem(codigo) ON DELETE RESTRICT ON UPDATE restrict;

alter table if exists documentoassinadopessoa  add column if not exists	nomepessoa varchar(255);
alter table if exists documentoassinadopessoa  add column if not exists	emailpessoa varchar(255);
alter table if exists documentoassinadopessoa  add column if not exists	cpfpessoa varchar(255);



