INSERT INTO public.configuracaogedorigem
( configuracaoged, tipoorigemdocumentoassinado, assinardocumento, apresentarassinaturadigitalizadofuncionario, apresentarselo, alturaselo, larguraselo, posicaoxselo, posicaoyselo, ultimapaginaselo, apresentarqrcode, alturaqrcode, larguraqrcode, posicaoxqrcode, posicaoyqrcode, ultimapaginaqrcode, assinaturaunidadeensino, apresentarassinaturaunidadeensino, alturaassinaturaunidadeensino, larguraassinaturaunidadeensino, posicaoxassinaturaunidadeensino, posicaoyassinaturaunidadeensino, ultimapaginaassinaturaunidadeensino, apresentarassinaturafuncionario1, alturaassinaturafuncionario1, larguraassinaturafuncionario1, posicaoxassinaturafuncionario1, posicaoyassinaturafuncionario1, ultimapaginaassinaturafuncionario1, apresentarassinaturafuncionario2, alturaassinaturafuncionario2, larguraassinaturafuncionario2, posicaoxassinaturafuncionario2, posicaoyassinaturafuncionario2, ultimapaginaassinaturafuncionario2, apresentarassinaturafuncionario3, alturaassinaturafuncionario3, larguraassinaturafuncionario3, posicaoxassinaturafuncionario3, posicaoyassinaturafuncionario3, ultimapaginaassinaturafuncionario3, assinardigitalmentediarioportodosprofessorescomaulaprogramada, assinardocumentofuncionarioresponsavel, created, codigocreated, nomecreated, updated, codigoupdated, nomeupdated, apresentarassinaturaaluno, alturaassinaturaaluno, larguraassinaturaaluno, posicaoxassinaturaaluno, posicaoyassinaturaaluno, ultimapaginaassinaturaaluno, provedorassinaturapadraoenum, permitiralunoassinardigitalmente)
VALUES( 1, 'PLANO_DE_ENSINO', true, true, false, 35, 35, 10, 10, true, true, 50, 50, 57, 10, true, true, true, 100, 150, 440, 10, true, false, 100, 100, 110, 10, true, false, 100, 100, 220, 10, true, false, 100, 100, 330, 10, true, false, false, NULL, NULL, NULL, '2023-01-27 13:03:15.184', 1272, 'nome102207', false, 100, 100, 330, 10, true, 'SEI', false);

ALTER TABLE if exists documentoassinado ADD if not exists planoensino integer;
select create_constraint ('ALTER TABLE public.documentoassinado ADD CONSTRAINT fk_documentoassinado_planoensino FOREIGN KEY (planoensino) REFERENCES planoensino(codigo) ON DELETE cascade;');

ALTER TABLE if exists planoensino ADD if not exists responsavelautorizacao integer;
select create_constraint ('ALTER TABLE public.planoensino add constraint fk_planoensino_responsavelautorizacao FOREIGN KEY (responsavelautorizacao) references usuario(codigo);');  
