package negocio.comuns.arquitetura.enumeradores;


public enum BloqueioFuncaoEnum {
	
	BLOQUEIO_NOTA_FISCAL,
	BLOQUEIO_TURMA_PROGRAMACAO_AULA,
	BLOQUEIO_PROFESSOR_TURMA_PROGRAMACAO_AULA,
	BLOQUEIO_PROCESSAMENTO_RROVA_PRESENCIAL,
	BLOQUEIO_UNIDADE_ENSINO_GERACAO_PARCELA,
	BLOQUEIO_TURMA_REALIZANDO_RENOVACAO;
	
}
