package negocio.comuns.arquitetura.enumeradores;

import negocio.comuns.utilitarias.UteisJSF;

/**
 * @author Wellington - 25 de set de 2015
 *
 */
public enum OperacaoFuncionalidadeEnum {

	DESATIVAR_FINANCEIRO_MANUAL, 
	ATIVAR_FINANCEIRO_MANUAL, 
	LIBERACAO_DESCONTO_ALUNO,
	LIBERAR_EDICAO_COM_SENHA,
    MATRICULA_LIBERARCONTROLEINCLUSAODISCIPLINAPERIODOFUTURO,
    MATRICULA_LIBERARINCLUSAODISCIPLINAPERIODOLETIVOFUTUROALUNOREGULAR,
    MATRICULA_LIBERAREXCLUSAODISCIPLINAPERIODOLETIVOATUALALUNOREGULAR,
    MATRICULA_LIBERAREXCLUSAODISCIPLINAPERIODOLETIVOATUALALUNOIRREGULAR,
    MATRICULA_LIBERARCONTROLEINCLUSAOOBRIGATORIADISCIPLINADEPENDENCIA,
    MATRICULA_LIBERARMATRICULATURMABASESEMVAGASEMAULA,
    MATRICULA_LIBERARALTERACAOCATEGORIAPLANOFINANCEIRO,
    MATRICULA_LIBERARALTERACAOCONTRATO,
    MATRICULA_LIBERARMATRICULADISICPLINASEMVAGA,
	MATRICULA_LIBERARMATRICULA_ALUNOPENDENTEFINANCEIRO,
	MATRICULA_LIBERARMATRICULA_OUTROPERIODOLETIVO,
	MATRICULA_LIBERARMATRICULA_INCLUSAODISCIPLINAFORAPRAZO,
	MATRICULA_LIBERARMATRICULA_INCLUSAODISCIPLINAPREREQUISITO,
	MATRICULA_LIBERARMATRICULA_PENDENCIADOCUMENTO,
	MATRICULA_LIBERARINCLUSAODISCIPLINAPOREQUIVALENCIA,
	MATRICULA_LIBERARINCLUSAODISCIPLINAOPTATIVA,
	MATRICULA_LIBERARINCLUSAODISCIPLINATURMAOUTROUNIDADEENSINO,
	MATRICULA_LIBERARINCLUSAODISCIPLINATURMAOUTROCURSO,
	MATRICULA_LIBERAR_INCLUSAO_DISCIPLINA_ACIMA_MAXIMO_PERMITIDO,
	MATRICULA_LIBERAR_INCLUSAO_DISCIPLINA_ABAIXO_MINIMO_PERMITIDO,
	MATRICULA_LIBERAR_OBRIGATORIEDADE_ALUNO_ACEITAR_TERMO_ACEITE,
	MATRICULA_PERMITIR_USUARIO_DESCONSIDERAR_DIFERENCA_VALOR_RATEIO,
	MATRICULA_PERMITIR_INFORMAR_NUMERO_MATRICULA_MANUALMENTE,
	PARCEIRO_LIBERAR_INCLUSAO_CONVENIO_DEBITO_FINANCEIRO,
	EXCLUIR_MOVIMENTACAO_FINANCEIRO_ITEM,
	REQUERIMENTO_ALTERAR_VALOR_DESCONTO,
	REQUERIMENTO_ALTERAR_ACRESCIMO,
	REQUERIMENTO_VOLTAR_SITUACAO_EXECUCAO,
	CONTA_RECEBER_LIBERAR_SUSPENSAO_CONVENIO,
	CONTA_RECEBER_LIBERAR_INDICE_REAJUSTE_ATRASO_,
	PROGRAMACAO_AULA_LIBERAR_COM_CHOQUE_HORARIO,
	NEGOCIACAO_CONTA_RECEBER_LIBERAR_ISENCAO_JURO_MULTA_DESCONTO,
	REQUISICAO_LIBERAR_ALTERACAO_ESTOQUE_RETIRADA,
	REQUISICAO_LIBERAR_VALOR_MAXIMO_COMPRA_DIRETA,
	ALTERAR_DATA_PROVA_ITEM_PROCESSO_SELETIVO,
	ALTERAR_DATA_TRANSFERENCIA_SAIDA,
	LIBERACAO_REATIVAR_MATRICULA_NUMERO_PERIODO_ULTRAPASSADO_AO_CONFIGURADO,
	REGISTROATIVIDADECOMPLEMENTARMATRICULA_LIBERARCARGAHORARIAMAXIMAPERIODOLETIVO,
	ATIVAR_SITUACAO_ULTIMA_MATRICULAPERIODO_ALUNO,
	ALTERAR_PLANO_FINANCEIRO_CATEGORIA_CONDICAO_PAGAMENTO,
	REMESSA_LIBERAR_ENVIAR_REMESSA_SEM_REAJUSTE_PRECO,
	LIBERACAO_ALTERACAO_PLANO_FINANCEIRO_TURMA,
	MATRICULA_PERMITIR_REGERAR_FINANCEIRO,
	IMPRESSAO_CONTRATO_LIBERARALTERACAOCONTRATO,
	MATRICULA_LIBERAR_VALIDACAO_DADOS_ENADE_CENSO,
	LIBERAR_MOVIMENTACAO_FINANCEIRA_CAIXA_FECHADO,
	MATRICULA_PERMITIR_LIBERAR_VALIDACAO_ALUNO_COM_BLOQUEIO_BIBLIOTECA,
	MATRICULA_PERMITIR_INCLUIR_PLANO_DESCONTO_DIFERENTE_CONDICAO_PAGAMENTO_DO_CURSO;

	public String getValorApresentar() {
		return UteisJSF.internacionalizar("enum_OperacaoFuncionalidadeEnum_" + this.name());
	}

}
