package negocio.comuns.administrativo.enumeradores;

/**
 * 
 * @author Pedro
 */
public enum TipoOrigemComunicacaoInternaEnum {
	NENHUM, OUVIDORIA, FALE_CONOSCO, SUPORTE_ALUNO, FINANCEIRO_COBRANCA, FOLLOW_ME,ANIVERSARIANTE, AVALIACAO_INSTITUCIONAL, SOLICITACAO_ORCAMENTO_PLANO_ORCAMENTARIO, 
	ITEM_REQUERIMENTO_INTERACAO, SOLICITAR_ALTERAR_SENHA,
	MENSAGEM_NOTIFICACAO_PROJETO_INTEGRADOR_INCLUSAO_SALA_GRUPO,
	MENSAGEM_NOTIFICACAO_PROJETO_INTEGRADOR_ALTERACAO_SALA_GRUPO,
	MENSAGEM_NOTIFICACAO_PROJETO_INTEGRADOR_EXCLUSAO_SALA_GRUPO,
	MENSAGEM_NOTIFICACAO_TCC_INCLUSAO_SALA_GRUPO, 
	MENSAGEM_NOTIFICACAO_TCC_ALTERACAO_SALA_GRUPO,
	MENSAGEM_NOTIFICACAO_TCC_EXCLUSAO_SALA_GRUPO

}
