package negocio.comuns.administrativo.enumeradores;


public enum PainelGestorTipoMonitoramentoCRMEnum {

    PRE_INSCRICAO, 
    PRE_INSCRICAO_DETALHE_CURSO, 
    PRE_INSCRICAO_DETALHE_CONSULTOR, 
    PRE_INSCRICAO_DETALHE_CURSO_CONSULTOR, 
    PRE_INSCRICAO_DETALHE_CONSULTOR_CURSO, 
    LIGACAO_RECEPTIVA, 
    LIGACAO_RECEPTIVA_DETALHE_CURSO, 
    LIGACAO_RECEPTIVA_DETALHE_CONSULTOR, 
    LIGACAO_RECEPTIVA_DETALHE_CONSULTOR_CURSO, 
    LIGACAO_RECEPTIVA_DETALHE_CURSO_CONSULTOR, 
    TAXA_CONVERSAO, 
    TAXA_CONVERSAO_CURSO, 
    TAXA_CONVERSAO_CONSULTOR, 
    TAXA_CONVERSAO_CONSULTOR_CURSO, 
    TAXA_CONVERSAO_CURSO_CONSULTOR, 
    COMO_FICOU_SABENDO_INSTITUICAO, 
    PROSPECT_POR_UNIDADE,
    PROSPECT_POR_CONSULTOR,
    PROSPECT_POR_CURSO,
    SEGMENTACAO_PROSPECT
    
}
