//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 09:08:01 AM BRST 
//


package webservice.nfse.londrina;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the Londrina package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: Londrina
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TcEstruturaDescricaoErros }
     * 
     */
    public TcEstruturaDescricaoErros createTcEstruturaDescricaoErros() {
        return new TcEstruturaDescricaoErros();
    }

    /**
     * Create an instance of {@link TcConsultarNfseServicoPrestadoEnvio }
     * 
     */
    public TcConsultarNfseServicoPrestadoEnvio createTcConsultarNfseServicoPrestadoEnvio() {
        return new TcConsultarNfseServicoPrestadoEnvio();
    }

    /**
     * Create an instance of {@link TcConsultarCadastroContribuinteEnvio }
     * 
     */
    public TcConsultarCadastroContribuinteEnvio createTcConsultarCadastroContribuinteEnvio() {
        return new TcConsultarCadastroContribuinteEnvio();
    }

    /**
     * Create an instance of {@link TcListaErrosAlertas }
     * 
     */
    public TcListaErrosAlertas createTcListaErrosAlertas() {
        return new TcListaErrosAlertas();
    }

    /**
     * Create an instance of {@link TcConsultarRpsServicoPrestadoEnvio }
     * 
     */
    public TcConsultarRpsServicoPrestadoEnvio createTcConsultarRpsServicoPrestadoEnvio() {
        return new TcConsultarRpsServicoPrestadoEnvio();
    }

    /**
     * Create an instance of {@link TcDescricaoRps }
     * 
     */
    public TcDescricaoRps createTcDescricaoRps() {
        return new TcDescricaoRps();
    }

    /**
     * Create an instance of {@link TcDescricaoCancelaNota }
     * 
     */
    public TcDescricaoCancelaNota createTcDescricaoCancelaNota() {
        return new TcDescricaoCancelaNota();
    }

    /**
     * Create an instance of {@link TcRetornoNota }
     * 
     */
    public TcRetornoNota createTcRetornoNota() {
        return new TcRetornoNota();
    }

}
