//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 09:08:01 AM BRST 
//


package webservice.nfse.londrina;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tcConsultarRpsServicoPrestadoEnvio complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcConsultarRpsServicoPrestadoEnvio">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ccm" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="cnpj" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cpf" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="senha" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="numero_rps" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="dia_rps" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="mes_rps" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ano_rps" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcConsultarRpsServicoPrestadoEnvio", propOrder = {
    "ccm",
    "cnpj",
    "cpf",
    "senha",
    "numeroRps",
    "diaRps",
    "mesRps",
    "anoRps"
})
public class TcConsultarRpsServicoPrestadoEnvio {

    protected int ccm;
    @XmlElement(required = true)
    protected String cnpj;
    @XmlElement(required = true)
    protected String cpf;
    @XmlElement(required = true)
    protected String senha;
    @XmlElement(name = "numero_rps")
    protected int numeroRps;
    @XmlElement(name = "dia_rps")
    protected int diaRps;
    @XmlElement(name = "mes_rps")
    protected int mesRps;
    @XmlElement(name = "ano_rps")
    protected int anoRps;

    /**
     * Gets the value of the ccm property.
     * 
     */
    public int getCcm() {
        return ccm;
    }

    /**
     * Sets the value of the ccm property.
     * 
     */
    public void setCcm(int value) {
        this.ccm = value;
    }

    /**
     * Gets the value of the cnpj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCnpj() {
        return cnpj;
    }

    /**
     * Sets the value of the cnpj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCnpj(String value) {
        this.cnpj = value;
    }

    /**
     * Gets the value of the cpf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpf() {
        return cpf;
    }

    /**
     * Sets the value of the cpf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpf(String value) {
        this.cpf = value;
    }

    /**
     * Gets the value of the senha property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenha() {
        return senha;
    }

    /**
     * Sets the value of the senha property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenha(String value) {
        this.senha = value;
    }

    /**
     * Gets the value of the numeroRps property.
     * 
     */
    public int getNumeroRps() {
        return numeroRps;
    }

    /**
     * Sets the value of the numeroRps property.
     * 
     */
    public void setNumeroRps(int value) {
        this.numeroRps = value;
    }

    /**
     * Gets the value of the diaRps property.
     * 
     */
    public int getDiaRps() {
        return diaRps;
    }

    /**
     * Sets the value of the diaRps property.
     * 
     */
    public void setDiaRps(int value) {
        this.diaRps = value;
    }

    /**
     * Gets the value of the mesRps property.
     * 
     */
    public int getMesRps() {
        return mesRps;
    }

    /**
     * Sets the value of the mesRps property.
     * 
     */
    public void setMesRps(int value) {
        this.mesRps = value;
    }

    /**
     * Gets the value of the anoRps property.
     * 
     */
    public int getAnoRps() {
        return anoRps;
    }

    /**
     * Sets the value of the anoRps property.
     * 
     */
    public void setAnoRps(int value) {
        this.anoRps = value;
    }

}
