//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 09:08:01 AM BRST 
//


package webservice.nfse.londrina;

import com.thoughtworks.xstream.annotations.XStreamAlias;


/**
 * <p>Java class for tcDescricaoRps complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * 
 * 
 */
@XStreamAlias("DescricaoRps")
public class TcDescricaoRps {

    protected int ccm;
    protected String cnpj;
    protected String cpf;
    protected String senha;
    protected String aliquota;
    protected int servico;
    protected String codigoObra;
    protected String obraArt;
    protected String situacao;
    protected String valor;
    protected String base;
    protected String ir;
    protected String pis;
    protected String cofins;
    protected String csll;
    protected String inss;
    @XStreamAlias("retencao_iss")
    protected String retencaoIss;
    @XStreamAlias("incentivo_fiscal")
    protected Integer incentivoFiscal;
    @XStreamAlias("cod_municipio_prestacao_servico")
    protected String codMunicipioPrestacaoServico;
    @XStreamAlias("cod_pais_prestacao_servico")
    protected String codPaisPrestacaoServico;
    @XStreamAlias("cod_municipio_incidencia")
    protected String codMunicipioIncidencia;
    protected String descricaoNF;
    @XStreamAlias("tomador_tipo")
    protected int tomadorTipo;
    @XStreamAlias("tomador_cnpj")
    protected String tomadorCnpj;
    @XStreamAlias("tomador_email")
    protected String tomadorEmail;
    @XStreamAlias("tomador_ie")
    protected String tomadorIe;
    @XStreamAlias("tomador_im")
    protected String tomadorIm;
    @XStreamAlias("tomador_razao")
    protected String tomadorRazao;
    @XStreamAlias("tomador_endereco")
    protected String tomadorEndereco;
    @XStreamAlias("tomador_numero")
    protected String tomadorNumero;
    @XStreamAlias("tomador_complemento")
    protected String tomadorComplemento;
    @XStreamAlias("tomador_bairro")
    protected String tomadorBairro;
    @XStreamAlias("tomador_CEP")
    protected String tomadorCEP;
    @XStreamAlias("tomador_cod_cidade")
    protected String tomadorCodCidade;
    @XStreamAlias("tomador_fone")
    protected String tomadorFone;
    @XStreamAlias("tomador_ramal")
    protected String tomadorRamal;
    @XStreamAlias("tomador_fax")
    protected String tomadorFax;
    @XStreamAlias("rps_num")
    protected Integer rpsNum;
    @XStreamAlias("rps_serie")
    protected String rpsSerie;
    @XStreamAlias("rps_tipo")
    protected Integer rpsTipo;
    @XStreamAlias("rps_dia")
    protected Integer rpsDia;
    @XStreamAlias("rps_mes")
    protected Integer rpsMes;
    @XStreamAlias("rps_ano")
    protected Integer rpsAno;
    @XStreamAlias("nfse_substituida")
    protected Integer nfseSubstituida;
    @XStreamAlias("rps_substituido")
    protected Integer rpsSubstituido;

    /**
     * Gets the value of the ccm property.
     * 
     */
    public int getCcm() {
        return ccm;
    }

    /**
     * Sets the value of the ccm property.
     * 
     */
    public void setCcm(int value) {
        this.ccm = value;
    }

    /**
     * Gets the value of the cnpj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCnpj() {
        return cnpj;
    }

    /**
     * Sets the value of the cnpj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCnpj(String value) {
        this.cnpj = value;
    }

    /**
     * Gets the value of the cpf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCpf() {
        return cpf;
    }

    /**
     * Sets the value of the cpf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCpf(String value) {
        this.cpf = value;
    }

    /**
     * Gets the value of the senha property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenha() {
        return senha;
    }

    /**
     * Sets the value of the senha property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenha(String value) {
        this.senha = value;
    }

    /**
     * Gets the value of the aliquota property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAliquota() {
        return aliquota;
    }

    /**
     * Sets the value of the aliquota property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliquota(String value) {
        this.aliquota = value;
    }

    /**
     * Gets the value of the servico property.
     * 
     */
    public int getServico() {
        return servico;
    }

    /**
     * Sets the value of the servico property.
     * 
     */
    public void setServico(int value) {
        this.servico = value;
    }

    /**
     * Gets the value of the codigoObra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoObra() {
        return codigoObra;
    }

    /**
     * Sets the value of the codigoObra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoObra(String value) {
        this.codigoObra = value;
    }

    /**
     * Gets the value of the obraArt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObraArt() {
        return obraArt;
    }

    /**
     * Sets the value of the obraArt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObraArt(String value) {
        this.obraArt = value;
    }

    /**
     * Gets the value of the situacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSituacao() {
        return situacao;
    }

    /**
     * Sets the value of the situacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSituacao(String value) {
        this.situacao = value;
    }

    /**
     * Gets the value of the valor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValor() {
        return valor;
    }

    /**
     * Sets the value of the valor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValor(String value) {
        this.valor = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

    /**
     * Gets the value of the ir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIr() {
        return ir;
    }

    /**
     * Sets the value of the ir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIr(String value) {
        this.ir = value;
    }

    /**
     * Gets the value of the pis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPis() {
        return pis;
    }

    /**
     * Sets the value of the pis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPis(String value) {
        this.pis = value;
    }

    /**
     * Gets the value of the cofins property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCofins() {
        return cofins;
    }

    /**
     * Sets the value of the cofins property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCofins(String value) {
        this.cofins = value;
    }

    /**
     * Gets the value of the csll property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCsll() {
        return csll;
    }

    /**
     * Sets the value of the csll property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCsll(String value) {
        this.csll = value;
    }

    /**
     * Gets the value of the inss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInss() {
        return inss;
    }

    /**
     * Sets the value of the inss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInss(String value) {
        this.inss = value;
    }

    /**
     * Gets the value of the retencaoIss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetencaoIss() {
        return retencaoIss;
    }

    /**
     * Sets the value of the retencaoIss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetencaoIss(String value) {
        this.retencaoIss = value;
    }

    /**
     * Gets the value of the incentivoFiscal property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIncentivoFiscal() {
        return incentivoFiscal;
    }

    /**
     * Sets the value of the incentivoFiscal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIncentivoFiscal(Integer value) {
        this.incentivoFiscal = value;
    }

    /**
     * Gets the value of the codMunicipioPrestacaoServico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodMunicipioPrestacaoServico() {
        return codMunicipioPrestacaoServico;
    }

    /**
     * Sets the value of the codMunicipioPrestacaoServico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodMunicipioPrestacaoServico(String value) {
        this.codMunicipioPrestacaoServico = value;
    }

    /**
     * Gets the value of the codPaisPrestacaoServico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodPaisPrestacaoServico() {
        return codPaisPrestacaoServico;
    }

    /**
     * Sets the value of the codPaisPrestacaoServico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodPaisPrestacaoServico(String value) {
        this.codPaisPrestacaoServico = value;
    }

    /**
     * Gets the value of the codMunicipioIncidencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodMunicipioIncidencia() {
        return codMunicipioIncidencia;
    }

    /**
     * Sets the value of the codMunicipioIncidencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodMunicipioIncidencia(String value) {
        this.codMunicipioIncidencia = value;
    }

    /**
     * Gets the value of the descricaoNF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescricaoNF() {
        return descricaoNF;
    }

    /**
     * Sets the value of the descricaoNF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescricaoNF(String value) {
        this.descricaoNF = value;
    }

    /**
     * Gets the value of the tomadorTipo property.
     * 
     */
    public int getTomadorTipo() {
        return tomadorTipo;
    }

    /**
     * Sets the value of the tomadorTipo property.
     * 
     */
    public void setTomadorTipo(int value) {
        this.tomadorTipo = value;
    }

    /**
     * Gets the value of the tomadorCnpj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomadorCnpj() {
        return tomadorCnpj;
    }

    /**
     * Sets the value of the tomadorCnpj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomadorCnpj(String value) {
        this.tomadorCnpj = value;
    }

    /**
     * Gets the value of the tomadorEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomadorEmail() {
        return tomadorEmail;
    }

    /**
     * Sets the value of the tomadorEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomadorEmail(String value) {
        this.tomadorEmail = value;
    }

    /**
     * Gets the value of the tomadorIe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomadorIe() {
        return tomadorIe;
    }

    /**
     * Sets the value of the tomadorIe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomadorIe(String value) {
        this.tomadorIe = value;
    }

    /**
     * Gets the value of the tomadorIm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomadorIm() {
        return tomadorIm;
    }

    /**
     * Sets the value of the tomadorIm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomadorIm(String value) {
        this.tomadorIm = value;
    }

    /**
     * Gets the value of the tomadorRazao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomadorRazao() {
        return tomadorRazao;
    }

    /**
     * Sets the value of the tomadorRazao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomadorRazao(String value) {
        this.tomadorRazao = value;
    }

    /**
     * Gets the value of the tomadorEndereco property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomadorEndereco() {
        return tomadorEndereco;
    }

    /**
     * Sets the value of the tomadorEndereco property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomadorEndereco(String value) {
        this.tomadorEndereco = value;
    }

    /**
     * Gets the value of the tomadorNumero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomadorNumero() {
        return tomadorNumero;
    }

    /**
     * Sets the value of the tomadorNumero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomadorNumero(String value) {
        this.tomadorNumero = value;
    }

    /**
     * Gets the value of the tomadorComplemento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomadorComplemento() {
        return tomadorComplemento;
    }

    /**
     * Sets the value of the tomadorComplemento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomadorComplemento(String value) {
        this.tomadorComplemento = value;
    }

    /**
     * Gets the value of the tomadorBairro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomadorBairro() {
        return tomadorBairro;
    }

    /**
     * Sets the value of the tomadorBairro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomadorBairro(String value) {
        this.tomadorBairro = value;
    }

    /**
     * Gets the value of the tomadorCEP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomadorCEP() {
        return tomadorCEP;
    }

    /**
     * Sets the value of the tomadorCEP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomadorCEP(String value) {
        this.tomadorCEP = value;
    }

    /**
     * Gets the value of the tomadorCodCidade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomadorCodCidade() {
        return tomadorCodCidade;
    }

    /**
     * Sets the value of the tomadorCodCidade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomadorCodCidade(String value) {
        this.tomadorCodCidade = value;
    }

    /**
     * Gets the value of the tomadorFone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomadorFone() {
        return tomadorFone;
    }

    /**
     * Sets the value of the tomadorFone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomadorFone(String value) {
        this.tomadorFone = value;
    }

    /**
     * Gets the value of the tomadorRamal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomadorRamal() {
        return tomadorRamal;
    }

    /**
     * Sets the value of the tomadorRamal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomadorRamal(String value) {
        this.tomadorRamal = value;
    }

    /**
     * Gets the value of the tomadorFax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTomadorFax() {
        return tomadorFax;
    }

    /**
     * Sets the value of the tomadorFax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTomadorFax(String value) {
        this.tomadorFax = value;
    }

    /**
     * Gets the value of the rpsNum property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRpsNum() {
        return rpsNum;
    }

    /**
     * Sets the value of the rpsNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRpsNum(Integer value) {
        this.rpsNum = value;
    }

    /**
     * Gets the value of the rpsSerie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRpsSerie() {
        return rpsSerie;
    }

    /**
     * Sets the value of the rpsSerie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRpsSerie(String value) {
        this.rpsSerie = value;
    }

    /**
     * Gets the value of the rpsTipo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRpsTipo() {
        return rpsTipo;
    }

    /**
     * Sets the value of the rpsTipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRpsTipo(Integer value) {
        this.rpsTipo = value;
    }

    /**
     * Gets the value of the rpsDia property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRpsDia() {
        return rpsDia;
    }

    /**
     * Sets the value of the rpsDia property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRpsDia(Integer value) {
        this.rpsDia = value;
    }

    /**
     * Gets the value of the rpsMes property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRpsMes() {
        return rpsMes;
    }

    /**
     * Sets the value of the rpsMes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRpsMes(Integer value) {
        this.rpsMes = value;
    }

    /**
     * Gets the value of the rpsAno property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRpsAno() {
        return rpsAno;
    }

    /**
     * Sets the value of the rpsAno property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRpsAno(Integer value) {
        this.rpsAno = value;
    }

    /**
     * Gets the value of the nfseSubstituida property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNfseSubstituida() {
        return nfseSubstituida;
    }

    /**
     * Sets the value of the nfseSubstituida property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNfseSubstituida(Integer value) {
        this.nfseSubstituida = value;
    }

    /**
     * Gets the value of the rpsSubstituido property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRpsSubstituido() {
        return rpsSubstituido;
    }

    /**
     * Sets the value of the rpsSubstituido property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRpsSubstituido(Integer value) {
        this.rpsSubstituido = value;
    }

	@Override
	public String toString() {
		return "TcDescricaoRps [ccm=" + ccm + ", cnpj=" + cnpj + ", cpf=" + cpf + ", senha=" + senha + ", aliquota=" + aliquota + ", servico=" + servico + ", codigoObra=" + codigoObra + ", obraArt=" + obraArt + ", situacao=" + situacao + ", valor=" + valor + ", base=" + base + ", ir=" + ir + ", pis=" + pis + ", cofins=" + cofins + ", csll=" + csll + ", inss=" + inss + ", retencaoIss=" + retencaoIss + ", incentivoFiscal=" + incentivoFiscal + ", codMunicipioPrestacaoServico=" + codMunicipioPrestacaoServico + ", codPaisPrestacaoServico=" + codPaisPrestacaoServico + ", codMunicipioIncidencia=" + codMunicipioIncidencia + ", descricaoNF=" + descricaoNF + ", tomadorTipo=" + tomadorTipo + ", tomadorCnpj=" + tomadorCnpj + ", tomadorEmail=" + tomadorEmail + ", tomadorIe=" + tomadorIe + ", tomadorIm=" + tomadorIm + ", tomadorRazao=" + tomadorRazao + ", tomadorEndereco=" + tomadorEndereco + ", tomadorNumero=" + tomadorNumero + ", tomadorComplemento=" + tomadorComplemento + ", tomadorBairro="
				+ tomadorBairro + ", tomadorCEP=" + tomadorCEP + ", tomadorCodCidade=" + tomadorCodCidade + ", tomadorFone=" + tomadorFone + ", tomadorRamal=" + tomadorRamal + ", tomadorFax=" + tomadorFax + ", rpsNum=" + rpsNum + ", rpsSerie=" + rpsSerie + ", rpsTipo=" + rpsTipo + ", rpsDia=" + rpsDia + ", rpsMes=" + rpsMes + ", rpsAno=" + rpsAno + ", nfseSubstituida=" + nfseSubstituida + ", rpsSubstituido=" + rpsSubstituido + "]";
	}
}
