package relatorio.negocio.comuns.painelGestor.enumeradores;

import negocio.comuns.utilitarias.UteisJSF;


public enum TipoRelatorioFollowMeEnum {
        
    RECEITA_DESPESA_TODAS_UNIDADES,
    RECEITA_DESPESA_TODAS_UNIDADES_PERIODO_ANTERIOR,
    RECEITA_DESPESA_UNIDADE_ESPECIFICA,
    RECEITA_DESPESA_UNIDADE_ESPECIFICA_PERIODO_ANTERIOR,
    
    DESPESA_TODAS_UNIDADES,
    DESPESA_TODAS_UNIDADES_PERIODO_ANTERIOR,
    DESPESA_UNIDADE_ESPECIFICA,
    DESPESA_UNIDADE_ESPECIFICA_PERIODO_ANTERIOR,
    
    CATEGORIA_DESPESA_TODAS_UNIDADES,
    CATEGORIA_DESPESA_TODAS_UNIDADES_PERIODO_ANTERIOR,
    CATEGORIA_DESPESA_UNIDADE_ESPECIFICA,
    CATEGORIA_DESPESA_UNIDADE_ESPECIFICA_PERIODO_ANTERIOR,
    CATEGORIA_DESPESA_TODAS_UNIDADES_AGRUPADO,
    CATEGORIA_DESPESA_TODAS_UNIDADES_PERIODO_ANTERIOR_AGRUPADO,
    CATEGORIA_DESPESA_UNIDADE_ESPECIFICA_AGRUPADO,
    CATEGORIA_DESPESA_UNIDADE_ESPECIFICA_PERIODO_ANTERIOR_AGRUPADO,
    
    CATEGORIA_DESPESA_TODAS_UNIDADES_PADRAO_ALTERADO,    
    CATEGORIA_DESPESA_UNIDADE_ESPECIFICA_PADRAO_ALTERADO,
    
    RECEITA_DESPESA_POR_NIVEL_EDUCACIONAL_TODAS_UNIDADES,
    RECEITA_DESPESA_POR_NIVEL_EDUCACIONAL_TODAS_UNIDADES_PERIODO_ANTERIOR,
    RECEITA_DESPESA_POR_NIVEL_EDUCACIONAL_UNIDADE_ESPECIFICA,
    RECEITA_DESPESA_POR_NIVEL_EDUCACIONAL_UNIDADE_ESPECIFICA_PERIODO_ANTERIOR,
    
    GASTO_POR_DEPARTAMENTO_UNIDADE_ESPECIFICA,    
    GASTO_POR_DEPARTAMENTO_TODAS_UNIDADES,
    
    ACADEMICO_FINANCEIRO_TODAS_UNIDADES,
    ACADEMICO_FINANCEIRO_UNIDADE_ESPECIFICA,
    
    POSICAO_FINANCEIRA,
    INADIMPLENCIA_TODAS_UNIDADES,
    INADIMPLENCIA_UNIDADE_ESPECIFICA;
    
    
    public String getValorApresentar(){
        return UteisJSF.internacionalizar("enum_TipoRelatorioFollowMeEnum_"+this.name());
    }
    

}
