//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.01 at 02:46:19 PM BRT 
//


package webservice.nfse.campogrande;
import java.math.BigDecimal;

import com.thoughtworks.xstream.annotations.XStreamAlias;


/**
 * Tipo Itens de Nota Fiscal.
 * 
 * <p>Java class for tpItens complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tpItens">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DiscriminacaoServico" type="{http://localhost:8080/WsNFe2/tp}tpDiscriminacao"/>
 *         &lt;element name="Quantidade" type="{http://localhost:8080/WsNFe2/tp}tpQuantidade"/>
 *         &lt;element name="ValorUnitario" type="{http://localhost:8080/WsNFe2/tp}tpValor4d"/>
 *         &lt;element name="ValorTotal" type="{http://localhost:8080/WsNFe2/tp}tpValor"/>
 *         &lt;element name="Tributavel" type="{http://localhost:8080/WsNFe2/tp}tpItemTributavel" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XStreamAlias(value = "Item")
public class TpItens {

	@XStreamAlias(value = "DiscriminacaoServico")
    protected String discriminacaoServico;
	@XStreamAlias(value = "Quantidade")
    protected BigDecimal quantidade;
	@XStreamAlias(value = "ValorUnitario")
    protected BigDecimal valorUnitario;
	@XStreamAlias(value = "ValorTotal")
    protected BigDecimal valorTotal;
	@XStreamAlias(value = "Tributavel")
    protected TpItemTributavel tributavel;

    /**
     * Gets the value of the discriminacaoServico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscriminacaoServico() {
        return discriminacaoServico;
    }

    /**
     * Sets the value of the discriminacaoServico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscriminacaoServico(String value) {
        this.discriminacaoServico = value;
    }

    /**
     * Gets the value of the quantidade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getQuantidade() {
        return quantidade;
    }

    /**
     * Sets the value of the quantidade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuantidade(BigDecimal value) {
        this.quantidade = value;
    }

    /**
     * Gets the value of the valorUnitario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getValorUnitario() {
        return valorUnitario;
    }

    /**
     * Sets the value of the valorUnitario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValorUnitario(BigDecimal value) {
        this.valorUnitario = value;
    }

    /**
     * Gets the value of the valorTotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public BigDecimal getValorTotal() {
        return valorTotal;
    }

    /**
     * Sets the value of the valorTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValorTotal(BigDecimal value) {
        this.valorTotal = value;
    }

    /**
     * Gets the value of the tributavel property.
     * 
     * @return
     *     possible object is
     *     {@link TpItemTributavel }
     *     
     */
    public TpItemTributavel getTributavel() {
        return tributavel;
    }

    /**
     * Sets the value of the tributavel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpItemTributavel }
     *     
     */
    public void setTributavel(TpItemTributavel value) {
        this.tributavel = value;
    }

	@Override
	public String toString() {
		return "TpItens [DiscriminacaoServico=" + discriminacaoServico + ", Quantidade=" + quantidade + ", ValorUnitario=" + valorUnitario + ", ValorTotal=" + valorTotal + ", Tributavel=" + tributavel + "]";
	}
}
