//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.01 at 02:46:19 PM BRT 
//


package webservice.nfse.belem;
import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;


/**
 * 
 * 
 */
@XStreamAlias(value = "ns1:ReqConsultaLote")
public class ReqConsultaLoteRPS {
	
	@XStreamAsAttribute
	@XStreamAlias(value= "xmlns:ns1")
	private String ns1 = "http://localhost:8080/WsNFe2/lote";
	@XStreamAsAttribute
	@XStreamAlias(value= "xmlns:tipos")
	private String tipos = "http://localhost:8080/WsNFe2/tp";
	@XStreamAsAttribute
	@XStreamAlias(value= "xmlns:xsi")
	private String xsi = "http://www.w3.org/2001/XMLSchema-instance";
	@XStreamAsAttribute
	@XStreamAlias(value= "xsi:schemaLocation")
	private String schemaLocation = "http://localhost:8080/WsNFe2/lote http://localhost:8080/WsNFe2/xsd/ReqConsultaLote.xsd";
    @XStreamAlias(value = "Cabecalho")
    protected webservice.nfse.belem.ReqConsultaLoteRPS.Cabecalho cabecalho;
    protected SignatureType signature;

    /**
     * Gets the value of the cabecalho property.
     * 
     * @return
     *     possible object is
     *     {@link ReqConsultaLoteRPS.Cabecalho }
     *     
     */
    public Cabecalho getCabecalho() {
        return cabecalho;
    }

    /**
     * Sets the value of the cabecalho property.
     * 
     * @param cabecalho2
     *     allowed object is
     *     {@link ReqConsultaLoteRPS.Cabecalho }
     *     
     */
    public void setCabecalho(webservice.nfse.belem.ReqConsultaLoteRPS.Cabecalho cabecalho2) {
        this.cabecalho = cabecalho2;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * 
     */
    @XStreamAlias(value = "Cabecalho")
    public static class Cabecalho {

    	@XStreamAlias("CodCidade")
        protected String codCidade;
    	@XStreamAlias("CPFCNPJRemetente")
        protected String cpfcnpjRemetente;
    	@XStreamAlias("Versao")
        protected long versao;
    	@XStreamAlias("NumeroLote")
    	protected String numeroLote;

        /**
         * Gets the value of the codCidade property.
         * 
         */
        public String getCodCidade() {
            return codCidade;
        }

        /**
         * Sets the value of the codCidade property.
         * 
         */
        public void setCodCidade(String value) {
            this.codCidade = value;
        }

        /**
         * Gets the value of the cpfcnpjRemetente property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCPFCNPJRemetente() {
            return cpfcnpjRemetente;
        }

        /**
         * Sets the value of the cpfcnpjRemetente property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCPFCNPJRemetente(String value) {
            this.cpfcnpjRemetente = value;
        }

       
        /**
         * Gets the value of the versao property.
         * 
         */
        public long getVersao() {
            return versao;
        }

        /**
         * Sets the value of the versao property.
         * 
         */
        public void setVersao(long value) {
            this.versao = value;
        }


		public String getNumeroLote() {
			return numeroLote;
		}

		public void setNumeroLote(String numeroLote) {
			this.numeroLote = numeroLote;
		}

		@Override
		public String toString() {
			return "Cabecalho [codCidade=" + codCidade + ", cpfcnpjRemetente=" + cpfcnpjRemetente + ", versao=" + versao + ", numeroLote=" + numeroLote + "]";
		}
    }
}
