//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.01 at 02:46:19 PM BRT 
//


package webservice.nfse.belem;
import java.math.BigDecimal;

import javax.xml.datatype.XMLGregorianCalendar;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamAsAttribute;


/**
 * 
 * 
 */
@XStreamAlias(value = "ns1:ReqEnvioLoteRPS")
public class ReqEnvioLoteRPS {
	
	@XStreamAsAttribute
	@XStreamAlias(value= "xmlns:ns1")
	private String ns1 = "http://localhost:8080/WsNFe2/lote";
	@XStreamAsAttribute
	@XStreamAlias(value= "xmlns:tipos")
	private String tipos = "http://localhost:8080/WsNFe2/tp";
	@XStreamAsAttribute
	@XStreamAlias(value= "xmlns:xsi")
	private String xsi = "http://www.w3.org/2001/XMLSchema-instance";
	@XStreamAsAttribute
	@XStreamAlias(value= "xsi:schemaLocation")
	private String schemaLocation = "http://localhost:8080/WsNFe2/lote http://localhost:8080/WsNFe2/xsd/ReqEnvioLoteRPS.xsd";
    @XStreamAlias(value = "Cabecalho")
    protected ReqEnvioLoteRPS.Cabecalho cabecalho;
    @XStreamAlias(value = "Lote")
    protected TpLote lote;
    protected SignatureType signature;

    /**
     * Gets the value of the cabecalho property.
     * 
     * @return
     *     possible object is
     *     {@link ReqEnvioLoteRPS.Cabecalho }
     *     
     */
    public ReqEnvioLoteRPS.Cabecalho getCabecalho() {
        return cabecalho;
    }

    /**
     * Sets the value of the cabecalho property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReqEnvioLoteRPS.Cabecalho }
     *     
     */
    public void setCabecalho(ReqEnvioLoteRPS.Cabecalho value) {
        this.cabecalho = value;
    }

    /**
     * Gets the value of the lote property.
     * 
     * @return
     *     possible object is
     *     {@link TpLote }
     *     
     */
    public TpLote getLote() {
        return lote;
    }

    /**
     * Sets the value of the lote property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpLote }
     *     
     */
    public void setLote(TpLote value) {
        this.lote = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * 
     */
    @XStreamAlias(value = "Cabecalho")
    public static class Cabecalho {

    	@XStreamAlias("CodCidade")
        protected String codCidade;
    	@XStreamAlias("CPFCNPJRemetente")
        protected String cpfcnpjRemetente;
    	@XStreamAlias("RazaoSocialRemetente")
        protected String razaoSocialRemetente;
    	@XStreamAlias("transacao")
        protected String transacao;
    	@XStreamAlias("dtInicio")
        protected String dtInicio;
    	@XStreamAlias("dtFim")
        protected String dtFim;
    	@XStreamAlias("QtdRPS")
        protected int qtdRPS;
    	@XStreamAlias("ValorTotalServicos")
        protected BigDecimal valorTotalServicos;
    	@XStreamAlias("ValorTotalDeducoes")
        protected BigDecimal valorTotalDeducoes;
    	@XStreamAlias("Versao")
        protected long versao;
    	@XStreamAlias("MetodoEnvio")
        protected TpMetodoEnvio metodoEnvio;
    	@XStreamAlias("VersaoComponente")
        protected String versaoComponente;

        /**
         * Gets the value of the codCidade property.
         * 
         */
        public String getCodCidade() {
            return codCidade;
        }

        /**
         * Sets the value of the codCidade property.
         * 
         */
        public void setCodCidade(String value) {
            this.codCidade = value;
        }

        /**
         * Gets the value of the cpfcnpjRemetente property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCPFCNPJRemetente() {
            return cpfcnpjRemetente;
        }

        /**
         * Sets the value of the cpfcnpjRemetente property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCPFCNPJRemetente(String value) {
            this.cpfcnpjRemetente = value;
        }

        /**
         * Gets the value of the razaoSocialRemetente property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRazaoSocialRemetente() {
            return razaoSocialRemetente;
        }

        /**
         * Sets the value of the razaoSocialRemetente property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRazaoSocialRemetente(String value) {
            this.razaoSocialRemetente = value;
        }

        /**
         * Gets the value of the transacao property.
         * 
         */
        public String getTransacao() {
            return transacao;
        }

        /**
         * Sets the value of the transacao property.
         * 
         */
        public void setTransacao(String value) {
            this.transacao = value;
        }

        /**
         * Gets the value of the dtInicio property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public String getDtInicio() {
            return dtInicio;
        }

        /**
         * Sets the value of the dtInicio property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDtInicio(String value) {
            this.dtInicio = value;
        }

        /**
         * Gets the value of the dtFim property.
         * 
         * @return
         *     
         */
        public String getDtFim() {
            return dtFim;
        }

        /**
         * Sets the value of the dtFim property.
         * 
         * @param value
         *     
         */
        public void setDtFim(String value) {
            this.dtFim = value;
        }

        /**
         * Gets the value of the qtdRPS property.
         * 
         */
        public int getQtdRPS() {
            return qtdRPS;
        }

        /**
         * Sets the value of the qtdRPS property.
         * 
         */
        public void setQtdRPS(int value) {
            this.qtdRPS = value;
        }

        /**
         * Gets the value of the valorTotalServicos property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getValorTotalServicos() {
            return valorTotalServicos;
        }

        /**
         * Sets the value of the valorTotalServicos property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setValorTotalServicos(BigDecimal value) {
            this.valorTotalServicos = value;
        }

        /**
         * Gets the value of the valorTotalDeducoes property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getValorTotalDeducoes() {
            return valorTotalDeducoes;
        }

        /**
         * Sets the value of the valorTotalDeducoes property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setValorTotalDeducoes(BigDecimal value) {
            this.valorTotalDeducoes = value;
        }

        /**
         * Gets the value of the versao property.
         * 
         */
        public long getVersao() {
            return versao;
        }

        /**
         * Sets the value of the versao property.
         * 
         */
        public void setVersao(long value) {
            this.versao = value;
        }

        /**
         * Gets the value of the metodoEnvio property.
         * 
         * @return
         *     possible object is
         *     {@link TpMetodoEnvio }
         *     
         */
        public TpMetodoEnvio getMetodoEnvio() {
            return metodoEnvio;
        }

        /**
         * Sets the value of the metodoEnvio property.
         * 
         * @param value
         *     allowed object is
         *     {@link TpMetodoEnvio }
         *     
         */
        public void setMetodoEnvio(TpMetodoEnvio value) {
            this.metodoEnvio = value;
        }

        /**
         * Gets the value of the versaoComponente property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersaoComponente() {
            return versaoComponente;
        }

        /**
         * Sets the value of the versaoComponente property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersaoComponente(String value) {
            this.versaoComponente = value;
        }

		@Override
		public String toString() {
			return "Cabecalho [CodCidade=" + codCidade + ", CPFCNPJRemetente=" + cpfcnpjRemetente + ", RazaoSocialRemetente=" + razaoSocialRemetente + ", Transacao=" + transacao + ", dtInicio=" + dtInicio + ", dtFim=" + dtFim + ", QtdRPS=" + qtdRPS + ", ValorTotalServicos=" + valorTotalServicos + ", ValorTotalDeducoes=" + valorTotalDeducoes + ", Versao=" + versao + ", MetodoEnvio=" + metodoEnvio + ", VersaoComponente=" + versaoComponente + "]";
		}
    }


	@Override
	public String toString() {
		return "ReqEnvioLoteRPS [Cabecalho=" + cabecalho + ", Lote=" + lote + ", Signature=" + signature + "]";
	}
}
