//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.01 at 02:46:19 PM BRT 
//


package webservice.nfse.belem;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

import com.thoughtworks.xstream.annotations.XStreamConverter;
import com.thoughtworks.xstream.converters.enums.EnumToStringConverter;


/**
 * <p>Java class for tpOperacao.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tpOperacao">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="B"/>
 *     &lt;enumeration value="C"/>
 *     &lt;enumeration value="D"/>
 *     &lt;enumeration value="J"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XStreamConverter(value = EnumToStringConverter.class)
public enum TpOperacao {


    /**
     * Sem Dedução.
     * 
     */
    A,

    /**
     * Com Dedução/Materiais.
     * 
     */
    B,

    /**
     * Imune/Isenta de ISSQN
     * 
     */
    C,

    /**
     * Devolução/Simples Remessa.
     * 
     */
    D,

    /**
     * Intermediação.
     * 
     */
    J;

    public String value() {
        return name();
    }

    public static TpOperacao fromValue(String v) {
        return valueOf(v);
    }

}
