//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 03:09:55 PM BRST 
//


package webservice.nfse.florianopolis;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tcDadosServico complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcDadosServico">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element name="ItemServico" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tcItemServico" maxOccurs="999"/>
 *           &lt;element name="BaseCalculo" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsValor"/>
 *           &lt;element name="ValorISSQN" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsValor"/>
 *           &lt;element name="BaseCalculoSubstituicao" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsValor" minOccurs="0"/>
 *           &lt;element name="ValorISSQNSubstituicao" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsValor" minOccurs="0"/>
 *           &lt;element name="ValorTotalServicos" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsValor"/>
 *           &lt;element name="DadosAdicionais" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsDadosAdicionais" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcDadosServico", namespace = "http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0", propOrder = {
    "itemServico",
    "baseCalculo",
    "valorISSQN",
    "baseCalculoSubstituicao",
    "valorISSQNSubstituicao",
    "valorTotalServicos",
    "dadosAdicionais"
})
public class TcDadosServico {

    @XmlElement(name = "ItemServico", required = true)
    protected List<TcItemServico> itemServico;
    @XmlElement(name = "BaseCalculo", required = true)
    protected BigDecimal baseCalculo;
    @XmlElement(name = "ValorISSQN", required = true)
    protected BigDecimal valorISSQN;
    @XmlElement(name = "BaseCalculoSubstituicao")
    protected BigDecimal baseCalculoSubstituicao;
    @XmlElement(name = "ValorISSQNSubstituicao")
    protected BigDecimal valorISSQNSubstituicao;
    @XmlElement(name = "ValorTotalServicos", required = true)
    protected BigDecimal valorTotalServicos;
    @XmlElement(name = "DadosAdicionais")
    protected String dadosAdicionais;

    /**
     * Gets the value of the itemServico property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemServico property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemServico().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TcItemServico }
     * 
     * 
     */
    public List<TcItemServico> getItemServico() {
        if (itemServico == null) {
            itemServico = new ArrayList<TcItemServico>();
        }
        return this.itemServico;
    }

    /**
     * Gets the value of the baseCalculo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBaseCalculo() {
        return baseCalculo;
    }

    /**
     * Sets the value of the baseCalculo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBaseCalculo(BigDecimal value) {
        this.baseCalculo = value;
    }

    /**
     * Gets the value of the valorISSQN property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorISSQN() {
        return valorISSQN;
    }

    /**
     * Sets the value of the valorISSQN property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorISSQN(BigDecimal value) {
        this.valorISSQN = value;
    }

    /**
     * Gets the value of the baseCalculoSubstituicao property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBaseCalculoSubstituicao() {
        return baseCalculoSubstituicao;
    }

    /**
     * Sets the value of the baseCalculoSubstituicao property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBaseCalculoSubstituicao(BigDecimal value) {
        this.baseCalculoSubstituicao = value;
    }

    /**
     * Gets the value of the valorISSQNSubstituicao property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorISSQNSubstituicao() {
        return valorISSQNSubstituicao;
    }

    /**
     * Sets the value of the valorISSQNSubstituicao property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorISSQNSubstituicao(BigDecimal value) {
        this.valorISSQNSubstituicao = value;
    }

    /**
     * Gets the value of the valorTotalServicos property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorTotalServicos() {
        return valorTotalServicos;
    }

    /**
     * Sets the value of the valorTotalServicos property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorTotalServicos(BigDecimal value) {
        this.valorTotalServicos = value;
    }

    /**
     * Gets the value of the dadosAdicionais property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDadosAdicionais() {
        return dadosAdicionais;
    }

    /**
     * Sets the value of the dadosAdicionais property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDadosAdicionais(String value) {
        this.dadosAdicionais = value;
    }

}
