//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 03:09:55 PM BRST 
//


package webservice.nfse.florianopolis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Tipo que representa um documento de identificação
 * 				do tomador.
 * 		
 * 
 * <p>Java class for tcDocIdTomador complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcDocIdTomador">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="CPFCNPJ" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tcCPFCNPJ"/>
 *         &lt;element name="Outros" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsOutrosDocIdentificacao"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcDocIdTomador", namespace = "http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0", propOrder = {
    "cpfcnpj",
    "outros"
})
public class TcDocIdTomador {

    @XmlElement(name = "CPFCNPJ")
    protected TcCPFCNPJ cpfcnpj;
    @XmlElement(name = "Outros")
    protected String outros;

    /**
     * Gets the value of the cpfcnpj property.
     * 
     * @return
     *     possible object is
     *     {@link TcCPFCNPJ }
     *     
     */
    public TcCPFCNPJ getCPFCNPJ() {
        return cpfcnpj;
    }

    /**
     * Sets the value of the cpfcnpj property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcCPFCNPJ }
     *     
     */
    public void setCPFCNPJ(TcCPFCNPJ value) {
        this.cpfcnpj = value;
    }

    /**
     * Gets the value of the outros property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutros() {
        return outros;
    }

    /**
     * Sets the value of the outros property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutros(String value) {
        this.outros = value;
    }

}
