//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 03:09:55 PM BRST 
//


package webservice.nfse.florianopolis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Tipo Endereço.
 * 
 * <p>Java class for tcEndereco complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcEndereco">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Logradouro" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsLogradouro"/>
 *         &lt;element name="NumeroEndereco" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsNumeroEndereco" minOccurs="0"/>
 *         &lt;element name="ComplementoEndereco" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsComplementoEndereco" minOccurs="0"/>
 *         &lt;element name="Bairro" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsBairro"/>
 *         &lt;element name="Municipio" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tcMunicipio"/>
 *         &lt;element name="CodigoPostal" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tcCodigoPostal"/>
 *         &lt;element name="UF" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsUF" minOccurs="0"/>
 *         &lt;element name="Pais" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsPais" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcEndereco", namespace = "http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0", propOrder = {
    "logradouro",
    "numeroEndereco",
    "complementoEndereco",
    "bairro",
    "municipio",
    "codigoPostal",
    "uf",
    "pais"
})
public class TcEndereco {

    @XmlElement(name = "Logradouro", required = true)
    protected String logradouro;
    @XmlElement(name = "NumeroEndereco")
    protected String numeroEndereco;
    @XmlElement(name = "ComplementoEndereco")
    protected String complementoEndereco;
    @XmlElement(name = "Bairro", required = true)
    protected String bairro;
    @XmlElement(name = "Municipio", required = true)
    protected TcMunicipio municipio;
    @XmlElement(name = "CodigoPostal", required = true)
    protected TcCodigoPostal codigoPostal;
    @XmlElement(name = "UF")
    protected String uf;
    @XmlElement(name = "Pais")
    protected Integer pais;

    /**
     * Gets the value of the logradouro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogradouro() {
        return logradouro;
    }

    /**
     * Sets the value of the logradouro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogradouro(String value) {
        this.logradouro = value;
    }

    /**
     * Gets the value of the numeroEndereco property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroEndereco() {
        return numeroEndereco;
    }

    /**
     * Sets the value of the numeroEndereco property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroEndereco(String value) {
        this.numeroEndereco = value;
    }

    /**
     * Gets the value of the complementoEndereco property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComplementoEndereco() {
        return complementoEndereco;
    }

    /**
     * Sets the value of the complementoEndereco property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComplementoEndereco(String value) {
        this.complementoEndereco = value;
    }

    /**
     * Gets the value of the bairro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBairro() {
        return bairro;
    }

    /**
     * Sets the value of the bairro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBairro(String value) {
        this.bairro = value;
    }

    /**
     * Gets the value of the municipio property.
     * 
     * @return
     *     possible object is
     *     {@link TcMunicipio }
     *     
     */
    public TcMunicipio getMunicipio() {
        return municipio;
    }

    /**
     * Sets the value of the municipio property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcMunicipio }
     *     
     */
    public void setMunicipio(TcMunicipio value) {
        this.municipio = value;
    }

    /**
     * Gets the value of the codigoPostal property.
     * 
     * @return
     *     possible object is
     *     {@link TcCodigoPostal }
     *     
     */
    public TcCodigoPostal getCodigoPostal() {
        return codigoPostal;
    }

    /**
     * Sets the value of the codigoPostal property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcCodigoPostal }
     *     
     */
    public void setCodigoPostal(TcCodigoPostal value) {
        this.codigoPostal = value;
    }

    /**
     * Gets the value of the uf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUF() {
        return uf;
    }

    /**
     * Sets the value of the uf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUF(String value) {
        this.uf = value;
    }

    /**
     * Gets the value of the pais property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPais() {
        return pais;
    }

    /**
     * Sets the value of the pais property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPais(Integer value) {
        this.pais = value;
    }

}
