//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 03:09:55 PM BRST 
//


package webservice.nfse.florianopolis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Dados da AEDF (Autorização para Emissão de
 * 				Documento Fiscal
 * 				Eletrônica).
 * 
 * <p>Java class for tcInformacaoAEDF complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcInformacaoAEDF">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AEDF" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsNumeroAEDF"/>
 *         &lt;element name="TipoAedf" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsTipoAedf"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcInformacaoAEDF", namespace = "http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0", propOrder = {
    "aedf",
    "tipoAedf"
})
public class TcInformacaoAEDF {

    @XmlElement(name = "AEDF", required = true)
    protected String aedf;
    @XmlElement(name = "TipoAedf", required = true)
    protected TsTipoAedf tipoAedf;

    /**
     * Gets the value of the aedf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAEDF() {
        return aedf;
    }

    /**
     * Sets the value of the aedf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAEDF(String value) {
        this.aedf = value;
    }

    /**
     * Gets the value of the tipoAedf property.
     * 
     * @return
     *     possible object is
     *     {@link TsTipoAedf }
     *     
     */
    public TsTipoAedf getTipoAedf() {
        return tipoAedf;
    }

    /**
     * Sets the value of the tipoAedf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TsTipoAedf }
     *     
     */
    public void setTipoAedf(TsTipoAedf value) {
        this.tipoAedf = value;
    }

}
