//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 03:09:55 PM BRST 
//


package webservice.nfse.florianopolis;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Tipo que representa uma requisição de NFPS-e.
 * 			
 * 
 * <p>Java class for tcInfRequisicao complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcInfRequisicao">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Versao" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsVersao"/>
 *         &lt;element name="TipoSistema" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsTipoSistema"/>
 *         &lt;element name="Identificacao" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsIdentificacaoRequisicao" minOccurs="0"/>
 *         &lt;element name="AEDF" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tcInformacaoAEDF"/>
 *         &lt;element name="CodigoVerificacao" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsCodigoVerificacao" minOccurs="0"/>
 *         &lt;element name="DataEmissao" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="NumeroSerieRequisicao" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsNumeroSerie" minOccurs="0"/>
 *         &lt;element name="NumeroSerieSubst" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsNumeroSerie" minOccurs="0"/>
 *         &lt;element name="CFPS" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsCFPS"/>
 *         &lt;element name="StatusRequisicao" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsStatusRequisicao" minOccurs="0"/>
 *         &lt;element name="DadosServico" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tcDadosServico"/>
 *         &lt;element name="Prestador" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tcDadosPrestador" minOccurs="0"/>
 *         &lt;element name="Tomador" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tcDadosTomador"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsIdTag" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcInfRequisicao", namespace = "http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0", propOrder = {
    "versao",
    "tipoSistema",
    "identificacao",
    "aedf",
    "codigoVerificacao",
    "dataEmissao",
    "numeroSerieRequisicao",
    "numeroSerieSubst",
    "cfps",
    "statusRequisicao",
    "dadosServico",
    "prestador",
    "tomador"
})
public class TcInfRequisicao {

    @XmlElement(name = "Versao", required = true)
    protected BigDecimal versao;
    @XmlElement(name = "TipoSistema")
    protected int tipoSistema;
    @XmlElement(name = "Identificacao")
    protected String identificacao;
    @XmlElement(name = "AEDF", required = true)
    protected TcInformacaoAEDF aedf;
    @XmlElement(name = "CodigoVerificacao")
    protected String codigoVerificacao;
    @XmlElement(name = "DataEmissao", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataEmissao;
    @XmlElement(name = "NumeroSerieRequisicao")
    protected Integer numeroSerieRequisicao;
    @XmlElement(name = "NumeroSerieSubst")
    protected Integer numeroSerieSubst;
    @XmlElement(name = "CFPS")
    protected int cfps;
    @XmlElement(name = "StatusRequisicao")
    protected Integer statusRequisicao;
    @XmlElement(name = "DadosServico", required = true)
    protected TcDadosServico dadosServico;
    @XmlElement(name = "Prestador")
    protected TcDadosPrestador prestador;
    @XmlElement(name = "Tomador", required = true)
    protected TcDadosTomador tomador;
    @XmlAttribute(name = "Id")
    protected String id;

    /**
     * Gets the value of the versao property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersao() {
        return versao;
    }

    /**
     * Sets the value of the versao property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersao(BigDecimal value) {
        this.versao = value;
    }

    /**
     * Gets the value of the tipoSistema property.
     * 
     */
    public int getTipoSistema() {
        return tipoSistema;
    }

    /**
     * Sets the value of the tipoSistema property.
     * 
     */
    public void setTipoSistema(int value) {
        this.tipoSistema = value;
    }

    /**
     * Gets the value of the identificacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificacao() {
        return identificacao;
    }

    /**
     * Sets the value of the identificacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificacao(String value) {
        this.identificacao = value;
    }

    /**
     * Gets the value of the aedf property.
     * 
     * @return
     *     possible object is
     *     {@link TcInformacaoAEDF }
     *     
     */
    public TcInformacaoAEDF getAEDF() {
        return aedf;
    }

    /**
     * Sets the value of the aedf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcInformacaoAEDF }
     *     
     */
    public void setAEDF(TcInformacaoAEDF value) {
        this.aedf = value;
    }

    /**
     * Gets the value of the codigoVerificacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoVerificacao() {
        return codigoVerificacao;
    }

    /**
     * Sets the value of the codigoVerificacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoVerificacao(String value) {
        this.codigoVerificacao = value;
    }

    /**
     * Gets the value of the dataEmissao property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataEmissao() {
        return dataEmissao;
    }

    /**
     * Sets the value of the dataEmissao property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataEmissao(XMLGregorianCalendar value) {
        this.dataEmissao = value;
    }

    /**
     * Gets the value of the numeroSerieRequisicao property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumeroSerieRequisicao() {
        return numeroSerieRequisicao;
    }

    /**
     * Sets the value of the numeroSerieRequisicao property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumeroSerieRequisicao(Integer value) {
        this.numeroSerieRequisicao = value;
    }

    /**
     * Gets the value of the numeroSerieSubst property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumeroSerieSubst() {
        return numeroSerieSubst;
    }

    /**
     * Sets the value of the numeroSerieSubst property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumeroSerieSubst(Integer value) {
        this.numeroSerieSubst = value;
    }

    /**
     * Gets the value of the cfps property.
     * 
     */
    public int getCFPS() {
        return cfps;
    }

    /**
     * Sets the value of the cfps property.
     * 
     */
    public void setCFPS(int value) {
        this.cfps = value;
    }

    /**
     * Gets the value of the statusRequisicao property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStatusRequisicao() {
        return statusRequisicao;
    }

    /**
     * Sets the value of the statusRequisicao property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStatusRequisicao(Integer value) {
        this.statusRequisicao = value;
    }

    /**
     * Gets the value of the dadosServico property.
     * 
     * @return
     *     possible object is
     *     {@link TcDadosServico }
     *     
     */
    public TcDadosServico getDadosServico() {
        return dadosServico;
    }

    /**
     * Sets the value of the dadosServico property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcDadosServico }
     *     
     */
    public void setDadosServico(TcDadosServico value) {
        this.dadosServico = value;
    }

    /**
     * Gets the value of the prestador property.
     * 
     * @return
     *     possible object is
     *     {@link TcDadosPrestador }
     *     
     */
    public TcDadosPrestador getPrestador() {
        return prestador;
    }

    /**
     * Sets the value of the prestador property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcDadosPrestador }
     *     
     */
    public void setPrestador(TcDadosPrestador value) {
        this.prestador = value;
    }

    /**
     * Gets the value of the tomador property.
     * 
     * @return
     *     possible object is
     *     {@link TcDadosTomador }
     *     
     */
    public TcDadosTomador getTomador() {
        return tomador;
    }

    /**
     * Sets the value of the tomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcDadosTomador }
     *     
     */
    public void setTomador(TcDadosTomador value) {
        this.tomador = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
