//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 03:09:55 PM BRST 
//


package webservice.nfse.florianopolis;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Tipo que representa uma NFPS-e.
 * 			
 * 
 * <p>Java class for tcInfNFPSe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcInfNFPSe">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Versao" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsVersao"/>
 *         &lt;element name="TipoSistema" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsTipoSistema"/>
 *         &lt;element name="Identificacao" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsIdentificacaoRequisicao" minOccurs="0"/>
 *         &lt;element name="AEDF" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tcInformacaoAEDF"/>
 *         &lt;element name="CodigoVerificacao" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsCodigoVerificacao" minOccurs="0"/>
 *         &lt;element name="NumeroSerie" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsNumeroSerie"/>
 *         &lt;element name="NumeroSerieSubst" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsNumeroSerie" minOccurs="0"/>
 *         &lt;element name="DataEmissao" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="DataProcessamento" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="DataCancelamento" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="MotivoCancelamento" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsDiscriminacao" minOccurs="0"/>
 *         &lt;element name="CFPS" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsCFPS"/>
 *         &lt;element name="CodigoCampanha" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsCodigoCampanha" minOccurs="0"/>
 *         &lt;element name="StatusNFPSe" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsStatusNFPSe"/>
 *         &lt;element name="DadosServico" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tcDadosServico"/>
 *         &lt;element name="Prestador" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tcDadosPrestador"/>
 *         &lt;element name="Tomador" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tcDadosTomador"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" use="required" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsIdTag" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcInfNFPSe", namespace = "http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0", propOrder = {
    "versao",
    "tipoSistema",
    "identificacao",
    "aedf",
    "codigoVerificacao",
    "numeroSerie",
    "numeroSerieSubst",
    "dataEmissao",
    "dataProcessamento",
    "dataCancelamento",
    "motivoCancelamento",
    "cfps",
    "codigoCampanha",
    "statusNFPSe",
    "dadosServico",
    "prestador",
    "tomador"
})
public class TcInfNFPSe {

    @XmlElement(name = "Versao", required = true)
    protected BigDecimal versao;
    @XmlElement(name = "TipoSistema")
    protected int tipoSistema;
    @XmlElement(name = "Identificacao")
    protected String identificacao;
    @XmlElement(name = "AEDF", required = true)
    protected TcInformacaoAEDF aedf;
    @XmlElement(name = "CodigoVerificacao")
    protected String codigoVerificacao;
    @XmlElement(name = "NumeroSerie")
    protected int numeroSerie;
    @XmlElement(name = "NumeroSerieSubst")
    protected Integer numeroSerieSubst;
    @XmlElement(name = "DataEmissao", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataEmissao;
    @XmlElement(name = "DataProcessamento", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataProcessamento;
    @XmlElement(name = "DataCancelamento")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dataCancelamento;
    @XmlElement(name = "MotivoCancelamento")
    protected String motivoCancelamento;
    @XmlElement(name = "CFPS")
    protected int cfps;
    @XmlElement(name = "CodigoCampanha")
    protected String codigoCampanha;
    @XmlElement(name = "StatusNFPSe")
    protected int statusNFPSe;
    @XmlElement(name = "DadosServico", required = true)
    protected TcDadosServico dadosServico;
    @XmlElement(name = "Prestador", required = true)
    protected TcDadosPrestador prestador;
    @XmlElement(name = "Tomador", required = true)
    protected TcDadosTomador tomador;
    @XmlAttribute(name = "Id", required = true)
    protected String id;

    /**
     * Gets the value of the versao property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersao() {
        return versao;
    }

    /**
     * Sets the value of the versao property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersao(BigDecimal value) {
        this.versao = value;
    }

    /**
     * Gets the value of the tipoSistema property.
     * 
     */
    public int getTipoSistema() {
        return tipoSistema;
    }

    /**
     * Sets the value of the tipoSistema property.
     * 
     */
    public void setTipoSistema(int value) {
        this.tipoSistema = value;
    }

    /**
     * Gets the value of the identificacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificacao() {
        return identificacao;
    }

    /**
     * Sets the value of the identificacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificacao(String value) {
        this.identificacao = value;
    }

    /**
     * Gets the value of the aedf property.
     * 
     * @return
     *     possible object is
     *     {@link TcInformacaoAEDF }
     *     
     */
    public TcInformacaoAEDF getAEDF() {
        return aedf;
    }

    /**
     * Sets the value of the aedf property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcInformacaoAEDF }
     *     
     */
    public void setAEDF(TcInformacaoAEDF value) {
        this.aedf = value;
    }

    /**
     * Gets the value of the codigoVerificacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoVerificacao() {
        return codigoVerificacao;
    }

    /**
     * Sets the value of the codigoVerificacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoVerificacao(String value) {
        this.codigoVerificacao = value;
    }

    /**
     * Gets the value of the numeroSerie property.
     * 
     */
    public int getNumeroSerie() {
        return numeroSerie;
    }

    /**
     * Sets the value of the numeroSerie property.
     * 
     */
    public void setNumeroSerie(int value) {
        this.numeroSerie = value;
    }

    /**
     * Gets the value of the numeroSerieSubst property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumeroSerieSubst() {
        return numeroSerieSubst;
    }

    /**
     * Sets the value of the numeroSerieSubst property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumeroSerieSubst(Integer value) {
        this.numeroSerieSubst = value;
    }

    /**
     * Gets the value of the dataEmissao property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataEmissao() {
        return dataEmissao;
    }

    /**
     * Sets the value of the dataEmissao property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataEmissao(XMLGregorianCalendar value) {
        this.dataEmissao = value;
    }

    /**
     * Gets the value of the dataProcessamento property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataProcessamento() {
        return dataProcessamento;
    }

    /**
     * Sets the value of the dataProcessamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataProcessamento(XMLGregorianCalendar value) {
        this.dataProcessamento = value;
    }

    /**
     * Gets the value of the dataCancelamento property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataCancelamento() {
        return dataCancelamento;
    }

    /**
     * Sets the value of the dataCancelamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataCancelamento(XMLGregorianCalendar value) {
        this.dataCancelamento = value;
    }

    /**
     * Gets the value of the motivoCancelamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotivoCancelamento() {
        return motivoCancelamento;
    }

    /**
     * Sets the value of the motivoCancelamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotivoCancelamento(String value) {
        this.motivoCancelamento = value;
    }

    /**
     * Gets the value of the cfps property.
     * 
     */
    public int getCFPS() {
        return cfps;
    }

    /**
     * Sets the value of the cfps property.
     * 
     */
    public void setCFPS(int value) {
        this.cfps = value;
    }

    /**
     * Gets the value of the codigoCampanha property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoCampanha() {
        return codigoCampanha;
    }

    /**
     * Sets the value of the codigoCampanha property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoCampanha(String value) {
        this.codigoCampanha = value;
    }

    /**
     * Gets the value of the statusNFPSe property.
     * 
     */
    public int getStatusNFPSe() {
        return statusNFPSe;
    }

    /**
     * Sets the value of the statusNFPSe property.
     * 
     */
    public void setStatusNFPSe(int value) {
        this.statusNFPSe = value;
    }

    /**
     * Gets the value of the dadosServico property.
     * 
     * @return
     *     possible object is
     *     {@link TcDadosServico }
     *     
     */
    public TcDadosServico getDadosServico() {
        return dadosServico;
    }

    /**
     * Sets the value of the dadosServico property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcDadosServico }
     *     
     */
    public void setDadosServico(TcDadosServico value) {
        this.dadosServico = value;
    }

    /**
     * Gets the value of the prestador property.
     * 
     * @return
     *     possible object is
     *     {@link TcDadosPrestador }
     *     
     */
    public TcDadosPrestador getPrestador() {
        return prestador;
    }

    /**
     * Sets the value of the prestador property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcDadosPrestador }
     *     
     */
    public void setPrestador(TcDadosPrestador value) {
        this.prestador = value;
    }

    /**
     * Gets the value of the tomador property.
     * 
     * @return
     *     possible object is
     *     {@link TcDadosTomador }
     *     
     */
    public TcDadosTomador getTomador() {
        return tomador;
    }

    /**
     * Sets the value of the tomador property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcDadosTomador }
     *     
     */
    public void setTomador(TcDadosTomador value) {
        this.tomador = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
