//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 03:09:55 PM BRST 
//


package webservice.nfse.florianopolis;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Tipo que representa uma requisição de cancelamento
 * 				de NFPS-e.
 * 			
 * 
 * <p>Java class for tcInfRequisicaoCancelamento complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcInfRequisicaoCancelamento">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Versao" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsVersao"/>
 *         &lt;element name="TipoSistema" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsTipoSistema"/>
 *         &lt;element name="AEDF" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsNumeroAEDF"/>
 *         &lt;element name="NumeroSerie" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsNumeroSerie"/>
 *         &lt;element name="MotivoCancelamento" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsDiscriminacao"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsIdTag" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcInfRequisicaoCancelamento", namespace = "http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0", propOrder = {
    "versao",
    "tipoSistema",
    "aedf",
    "numeroSerie",
    "motivoCancelamento"
})
public class TcInfRequisicaoCancelamento {

    @XmlElement(name = "Versao", required = true)
    protected BigDecimal versao;
    @XmlElement(name = "TipoSistema")
    protected int tipoSistema;
    @XmlElement(name = "AEDF", required = true)
    protected String aedf;
    @XmlElement(name = "NumeroSerie")
    protected int numeroSerie;
    @XmlElement(name = "MotivoCancelamento", required = true)
    protected String motivoCancelamento;
    @XmlAttribute(name = "Id")
    protected String id;

    /**
     * Gets the value of the versao property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersao() {
        return versao;
    }

    /**
     * Sets the value of the versao property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersao(BigDecimal value) {
        this.versao = value;
    }

    /**
     * Gets the value of the tipoSistema property.
     * 
     */
    public int getTipoSistema() {
        return tipoSistema;
    }

    /**
     * Sets the value of the tipoSistema property.
     * 
     */
    public void setTipoSistema(int value) {
        this.tipoSistema = value;
    }

    /**
     * Gets the value of the aedf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAEDF() {
        return aedf;
    }

    /**
     * Sets the value of the aedf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAEDF(String value) {
        this.aedf = value;
    }

    /**
     * Gets the value of the numeroSerie property.
     * 
     */
    public int getNumeroSerie() {
        return numeroSerie;
    }

    /**
     * Sets the value of the numeroSerie property.
     * 
     */
    public void setNumeroSerie(int value) {
        this.numeroSerie = value;
    }

    /**
     * Gets the value of the motivoCancelamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotivoCancelamento() {
        return motivoCancelamento;
    }

    /**
     * Sets the value of the motivoCancelamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotivoCancelamento(String value) {
        this.motivoCancelamento = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
