//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 03:09:55 PM BRST 
//


package webservice.nfse.florianopolis;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tcItemServico complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcItemServico">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element name="IdCNAE" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsIdCNAE"/>
 *           &lt;element name="CodigoAtividade" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsCodigoAtividade"/>
 *           &lt;element name="DescricaoServico" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsDiscriminacao"/>
 *           &lt;element name="CST" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsCST"/>
 *           &lt;element name="Aliquota" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsAliquota"/>
 *           &lt;element name="ValorUnitario" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsValor"/>
 *           &lt;element name="Quantidade" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsQuantidade"/>
 *           &lt;element name="ValorTotal" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsValor"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcItemServico", namespace = "http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0", propOrder = {
    "idCNAE",
    "codigoAtividade",
    "descricaoServico",
    "cst",
    "aliquota",
    "valorUnitario",
    "quantidade",
    "valorTotal"
})
public class TcItemServico {

    @XmlElement(name = "IdCNAE")
    protected int idCNAE;
    @XmlElement(name = "CodigoAtividade")
    protected String codigoAtividade;
    @XmlElement(name = "DescricaoServico", required = true)
    protected String descricaoServico;
    @XmlElement(name = "CST")
    protected int cst;
    @XmlElement(name = "Aliquota", required = true)
    protected BigDecimal aliquota;
    @XmlElement(name = "ValorUnitario", required = true)
    protected BigDecimal valorUnitario;
    @XmlElement(name = "Quantidade")
    protected int quantidade;
    @XmlElement(name = "ValorTotal", required = true)
    protected BigDecimal valorTotal;

    /**
     * Gets the value of the idCNAE property.
     * 
     */
    public int getIdCNAE() {
        return idCNAE;
    }

    /**
     * Sets the value of the idCNAE property.
     * 
     */
    public void setIdCNAE(int value) {
        this.idCNAE = value;
    }

    /**
     * Gets the value of the codigoAtividade property.
     * 
     */
    public String getCodigoAtividade() {
        return codigoAtividade;
    }

    /**
     * Sets the value of the codigoAtividade property.
     * 
     */
    public void setCodigoAtividade(String value) {
        this.codigoAtividade = value;
    }

    /**
     * Gets the value of the descricaoServico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescricaoServico() {
        return descricaoServico;
    }

    /**
     * Sets the value of the descricaoServico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescricaoServico(String value) {
        this.descricaoServico = value;
    }

    /**
     * Gets the value of the cst property.
     * 
     */
    public int getCST() {
        return cst;
    }

    /**
     * Sets the value of the cst property.
     * 
     */
    public void setCST(int value) {
        this.cst = value;
    }

    /**
     * Gets the value of the aliquota property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAliquota() {
        return aliquota;
    }

    /**
     * Sets the value of the aliquota property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAliquota(BigDecimal value) {
        this.aliquota = value;
    }

    /**
     * Gets the value of the valorUnitario property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorUnitario() {
        return valorUnitario;
    }

    /**
     * Sets the value of the valorUnitario property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorUnitario(BigDecimal value) {
        this.valorUnitario = value;
    }

    /**
     * Gets the value of the quantidade property.
     * 
     */
    public int getQuantidade() {
        return quantidade;
    }

    /**
     * Sets the value of the quantidade property.
     * 
     */
    public void setQuantidade(int value) {
        this.quantidade = value;
    }

    /**
     * Gets the value of the valorTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorTotal() {
        return valorTotal;
    }

    /**
     * Sets the value of the valorTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorTotal(BigDecimal value) {
        this.valorTotal = value;
    }

}
