//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 03:09:55 PM BRST 
//


package webservice.nfse.florianopolis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Tipo NFPSe.
 * 
 * <p>Java class for tcNFPSe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcNFPSe">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InfNFPSe" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tcInfNFPSe"/>
 *         &lt;element name="Protocolo" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tcProtocolo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcNFPSe", namespace = "http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0", propOrder = {
    "infNFPSe",
    "protocolo"
})
public class TcNFPSe {

    @XmlElement(name = "InfNFPSe", required = true)
    protected TcInfNFPSe infNFPSe;
    @XmlElement(name = "Protocolo")
    protected TcProtocolo protocolo;

    /**
     * Gets the value of the infNFPSe property.
     * 
     * @return
     *     possible object is
     *     {@link TcInfNFPSe }
     *     
     */
    public TcInfNFPSe getInfNFPSe() {
        return infNFPSe;
    }

    /**
     * Sets the value of the infNFPSe property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcInfNFPSe }
     *     
     */
    public void setInfNFPSe(TcInfNFPSe value) {
        this.infNFPSe = value;
    }

    /**
     * Gets the value of the protocolo property.
     * 
     * @return
     *     possible object is
     *     {@link TcProtocolo }
     *     
     */
    public TcProtocolo getProtocolo() {
        return protocolo;
    }

    /**
     * Sets the value of the protocolo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcProtocolo }
     *     
     */
    public void setProtocolo(TcProtocolo value) {
        this.protocolo = value;
    }

}
