//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 03:09:55 PM BRST 
//


package webservice.nfse.florianopolis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Tipo Requisicao de Cancelamento.
 * 			
 * 
 * <p>Java class for tcRequisicaoCancelamento complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcRequisicaoCancelamento">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InfRequisicaoCancelamento" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tcInfRequisicaoCancelamento"/>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature" minOccurs="0"/>
 *         &lt;element name="Autenticacao" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsAutenticacao" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcRequisicaoCancelamento", namespace = "http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0", propOrder = {
    "infRequisicaoCancelamento",
    "signature",
    "autenticacao"
})
public class TcRequisicaoCancelamento {

    @XmlElement(name = "InfRequisicaoCancelamento", required = true)
    protected TcInfRequisicaoCancelamento infRequisicaoCancelamento;
    @XmlElement(name = "Autenticacao")
    protected String autenticacao;

    /**
     * Gets the value of the infRequisicaoCancelamento property.
     * 
     * @return
     *     possible object is
     *     {@link TcInfRequisicaoCancelamento }
     *     
     */
    public TcInfRequisicaoCancelamento getInfRequisicaoCancelamento() {
        return infRequisicaoCancelamento;
    }

    /**
     * Sets the value of the infRequisicaoCancelamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcInfRequisicaoCancelamento }
     *     
     */
    public void setInfRequisicaoCancelamento(TcInfRequisicaoCancelamento value) {
        this.infRequisicaoCancelamento = value;
    }

    /**
     * Gets the value of the autenticacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutenticacao() {
        return autenticacao;
    }

    /**
     * Sets the value of the autenticacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutenticacao(String value) {
        this.autenticacao = value;
    }

}
