//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 03:09:55 PM BRST 
//


package webservice.nfse.florianopolis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Tipo Requisicao.
 * 
 * <p>Java class for tcRequisicao complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcRequisicao">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InfRequisicao" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tcInfRequisicao"/>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature" minOccurs="0"/>
 *         &lt;element name="Autenticacao" type="{http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0}tsAutenticacao" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcRequisicao", namespace = "http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0", propOrder = {
    "infRequisicao",
    "signature",
    "autenticacao"
})
public class TcRequisicao {

    @XmlElement(name = "InfRequisicao", required = true)
    protected TcInfRequisicao infRequisicao;
    @XmlElement(name = "Autenticacao")
    protected String autenticacao;

    /**
     * Gets the value of the infRequisicao property.
     * 
     * @return
     *     possible object is
     *     {@link TcInfRequisicao }
     *     
     */
    public TcInfRequisicao getInfRequisicao() {
        return infRequisicao;
    }

    /**
     * Sets the value of the infRequisicao property.
     * 
     * @param value
     *     allowed object is
     *     {@link TcInfRequisicao }
     *     
     */
    public void setInfRequisicao(TcInfRequisicao value) {
        this.infRequisicao = value;
    }

    /**
     * Gets the value of the autenticacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutenticacao() {
        return autenticacao;
    }

    /**
     * Sets the value of the autenticacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutenticacao(String value) {
        this.autenticacao = value;
    }

}
