//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 03:09:55 PM BRST 
//


package webservice.nfse.florianopolis;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tsTipoAedf.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tsTipoAedf">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NORMAL"/>
 *     &lt;enumeration value="FATURA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tsTipoAedf", namespace = "http://nfe.pmf.sc.gov.br/nfse/versao?tipo=xsd-2_0")
@XmlEnum
public enum TsTipoAedf {

    NORMAL,
    FATURA;

    public String value() {
        return name();
    }

    public static TsTipoAedf fromValue(String v) {
        return valueOf(v);
    }

}
