package negocio.comuns.estagio.enumeradores;

public enum MotivosPadroesEstagioCasoUsoEnum {
	NENHUM,
	/**
	 * Estagio Obrigatorio
	 */
	RETORNO_SOLICITACAO_APROVEITAMENTO,
	INDEFERIMENTO_SOLICITACAO_APROVEITAMENTO,
	RETORNO_SOLICITACAO_EQUIVALENCIA,
	INDEFERIMENTO_SOLICITACAO_EQUIVALENCIA,

	/**
	 * Estagio Não Obrigatorio
	 */
	RETORNO_AVALIACAO_TERMO,
	INDEFERIMENTO_AVALIACAO_TERMO,
	RETORNO_AVALIACAO_RELATORIO_FINAL,
	INDEFERIMENTO_AVALIACAO_RELATORIO_FINAL,
	RETORNO_ADITIVOS,
	INDEFERIMENTO_ADITIVOS,
	RETORNO_RECISAO,
	INDEFERIMENTO_RECISAO;

}
