CREATE TABLE if not exists calendariorelatoriofinalfacilitador (
	codigo serial4 NOT NULL,
	disciplina int4 NOT NULL,
	dataInicio timestamp NOT NULL,
	dataFim timestamp NOT NULL,
	mes varchar(10) NOT NULL,
	ano varchar(4) NOT NULL,
	semestre varchar(2) NOT NULL,
	questionario int4 NULL,
	variaveltiponota varchar(2) NOT NULL,
	created timestamp NULL,
	codigocreated int4 NULL,
	nomecreated varchar(255) NULL,
	updated timestamp NULL,
	codigoupdated int4 NULL,
	nomeupdated varchar(255) NULL,
	CONSTRAINT pkey_relatorioFinalDisciplinaFacilitador PRIMARY KEY (codigo),
	CONSTRAINT fk_relatorioFinalDisciplinaFacilitador_disciplina FOREIGN KEY (disciplina) REFERENCES public.disciplina(codigo) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_relatorioFinalDisciplinaFacilitador_questionario FOREIGN KEY (questionario) REFERENCES public.questionario(codigo) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE if not exists relatoriofinalfacilitador  (
	codigo serial4 NOT NULL,
	matriculaperiodoturmadisciplina int4 NOT NULL,
	dataEnvioAnalise timestamp  NULL,
	dataEnvioCorrecao timestamp  NULL,
	dataDeferimento timestamp  NULL,
	dataIndeferimento timestamp  NULL,
	situacao varchar(255) NULL,
	mes varchar(10) NULL,
	ano varchar(4) NULL,
	semestre varchar(2) NULL,
	questionarioRespostaOrigem int4 NULL,
	nota float4 NULL,
	supervisor int4 not null,
	motivo text null,
	responsavelSituacao VARCHAR(255) null,
	dataSituacao TIMESTAMP null,
	created timestamp NULL,
	codigocreated int4 NULL,
	nomecreated varchar(255) NULL,
	updated timestamp NULL,
	codigoupdated int4 NULL,
	nomeupdated varchar(255) NULL,
	CONSTRAINT pkey_relatorioFinalFacilitador PRIMARY KEY (codigo),
	CONSTRAINT fk_relatorioFinalFacilitador_matriculaperiodoturmadisciplina FOREIGN KEY (matriculaperiodoturmadisciplina) REFERENCES public.matriculaperiodoturmadisciplina(codigo) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_relatorioFinalFacilitador_questionarioRespostaOrigem FOREIGN KEY (questionarioRespostaOrigem) REFERENCES public.questionarioRespostaOrigem(codigo) ON DELETE CASCADE ON UPDATE cascade,
	CONSTRAINT fk_relatorioFinalFacilitador_supervisor FOREIGN KEY (supervisor) REFERENCES public.pessoa(codigo) ON DELETE CASCADE ON UPDATE CASCADE
);
