package negocio.comuns.crm.enumerador;

public enum TipoFiltroMonitamentoCrmProspectEnum {
	TODOS_PROSPECTS_CADASTRADOS,
	TODOS_PROSPECTS_COM_AGENDA,
	TODOS_PROSPECTS_SEM_AGENDA,
	TODOS_PROSPECTS_SEM_CONSULTOR,
	TODOS_PROSPECTS_COM_CONSULTOR,
	TODOS_PROSPECTS_SEM_CONTATO_PERIODO1,
	TODOS_PROSPECTS_SEM_CONTATO_PERIODO2,
	TODOS_PROSPECTS_SEM_CONTATO_PERIODO3,
	MES_ANO_ABORDADO,
	MES_ANO_FINALIZADO_SUCESSO,
	MES_ANO_MATRICULADO,
	MES_ANO_REAGENDADO,
	COMO_FICOU_SABENDO_INSTITUICAO,
	SEGMENTACAO_PROSPECT
	
}
