package negocio.comuns.utilitarias;

public enum TipoFiltroConsultaEnum {
	AREA_CONHECIMENTO, TIPO_CATALOGO, AUTOR, CURSO, DISCIPLINA,TITULO,ASSUNTO,PALAVRA_CHAVE,AUTORES,CLASSIFICACAO,ISBN,ISSN,CUTTER_PHA,TOMBO,SUBTITULO;
		
}
